"use client";

// Shared RunTimelineChartLabels fixture for the run-timeline component tests:
// the chart, strip, legend, and message panel all consume the same labels
// object, so one English fixture keeps their tests in step with the en
// message catalog's shape.

import type { RunTimelineChartLabels } from "@/components/run-timeline/run-timeline-details";

export function runTimelineLabels(): RunTimelineChartLabels {
  return {
    chart: "Timeline chart",
    visualization: "Timeline visualization",
    time: "Time",
    eventRail: "Event rail",
    input: "Input",
    output: "Output",
    turn: "Turn",
    bucket: "Bucket",
    cost: "Cost",
    model: "Model",
    empty: "No activity in this window.",
    moreEvents: (count, summary) => `+${count} more (${summary})`,
    turnDetails: "Turn details",
    timeRange: "Time range",
    activeSeconds: "Active seconds",
    latency: "Latency",
    executions: "Executions",
    tool: "Tool",
    status: "Status",
    succeeded: "Succeeded",
    failed: "Failed",
    anomalies: "Anomalies",
    none: "None",
    noExecutions: "No executions",
    closeDetails: "Close details",
    eventDetails: "Event details",
    layerDetails: "Layer details",
    layerSummary: "Summary",
    pendingLabel: "Pending",
    pendingExplainer: "Pending layer segment",
    pendingAria: "Pending layer segment",
    showMore: "Show more",
    showLess: "Show less",
    kind: "Kind",
    timestamp: "Timestamp",
    detail: "Detail",
    crumbRoot: "Initial window",
    readoutIdle: "Wheel / drag to pan · Ctrl+wheel to zoom · hover for info · click to read",
    stripAria: "Raw context messages",
    stripTruncated: "Earlier messages are not shown",
    stripMessageAria: (idx, kind, time, chars) => `Message ${idx} · ${kind} · ${time} · ${chars} chars`,
    stripPartLabels: {
      think: "agent thinking",
      text: "text output",
      call: "tool call",
      out: "tool output",
      note: "system note",
      "ib-agent": "inbound · agent",
      "ib-user": "inbound · user",
      "ib-sys": "inbound · system",
      compact: "compact summary",
      prompt: "system prompt",
      other: "other",
    },
    legendTitle: "Message categories",
    legendHint: "Click a category to highlight matching messages; click again to clear.",
    legendLabels: {
      think: "thinking",
      text: "text output",
      call: "tool call",
      out: "tool output",
      note: "system note",
      "ib-agent": "agent inbound",
      "ib-user": "user",
      sys: "compact / system",
      prompt: "system prompt",
    },
    readoutMessage: (idx, kind, time, chars, leaf) =>
      `#${idx} · ${kind} · ${time} · ${chars} chars \uFF5C summary: ${leaf ?? "None"}`,
    messageDetails: "Message details",
    messageCharsLabel: "Chars",
    messageSource: "Source",
    messageLabel: (idx) => `Message ${idx}`,
    messageChars: (chars) => `${chars} chars`,
    messagePart: (kind, chars) => `${kind} · ${chars} chars`,
    messageChain: "Covering summary blocks",
    messageFocus: "Zoom to this message",
    messageShowSummary: "View summary block",
    messageBody: "Message text",
    messageLoading: "Loading message…",
    messageLoadFailed: "Could not load the message.",
    messageExpandFull: "Show full text",
    messagePartTruncated: "truncated",
    messageNoText: "No text",
    retry: "Retry",
    railHidden: "Event rail is only visible on the time axis.",
    railHiddenPending: "Event rail and pending placeholders are only visible on the time axis.",
    readoutPosition: (position) => `position ${position}`,
    charsUnit: "chars",
    charTicks: "Character counts",
  };
}
