"""Code execution output envelope: format / truncate / overflow-to-file.

The exec node (`_exec.py`) runs agent code and collects its merged stdout+stderr
stream; this module turns that raw stream into the "Code execution output:"
envelope fed back to the LLM. Split out from `_exec.py` to keep that file's line
budget — this is a self-contained formatting layer with one public entry,
`wrap_code_output`, called by the exec node's result dispatch.

Long multiline output can first use a configurable line preview backed by a
full archive protected while the current context references it (`_exec_crop`).
The existing hard inline cap uses a separate 20-file ring under `.exec_output/`
in the agent's workspace. Neither archive lives in the OS temporary directory.

The hard inline limit is the SECOND of two hard caps. The first (`_exec_stream.StreamingTextIO`)
bounds accumulation while the code is still running; when it fired, its
`StreamCap` travels here so this layer reports the true produced length and
stops promising the archive holds the full text — the middle was dropped before
the archive was ever written. The accumulation budget is validated to be >=
`exec_output_max_chars`, so `truncate_both_ends` always slices its head out of
the accumulator's kept head and its tail out of the kept tail.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from langchain_core.messages import BaseMessage

import ava
import ava._boot
from shared.config import now_timestamp, settings
from shared.log import logger
from shared.paths import workspace_dir

from ._exec_crop import crop_output
from ._exec_stream import StreamCap

# Marker for exec cancel — thread really ran and was interrupted by user pressing Stop;
# wrap_code_output adds "Code execution output [cancelled by user]:" prefix to the envelope,
# EXEC_CANCEL_NOTE is kept as the substring existing tests assert against.
EXEC_CANCEL_NOTE = "[cancelled by user]"

# exec_timeout_seconds and exec_output_max_chars are read from shared.config.settings,
# no longer hardcoded at module level. EXEC_TIMEOUT_NOTE is dynamically generated by wrap_code_output.

# Overflow output is written into the agent's workspace so the agent can read /
# grep the complete output even when only head + tail are shown inline — and it
# survives OS temp-dir reaping and reboots, so day-old output stays greppable.
# Sibling of `.shell_logs/` (background-run logs): both live in the workspace,
# the default base of the agent's file and shell tools.
_OVERFLOW_DIRNAME = ".exec_output"
# Ring: keep the most recent N overflow files per workspace, prune older ones
# so the dir doesn't grow unbounded across a long-lived agent.
_OVERFLOW_KEEP = 20


def _overflow_dir() -> Path:
    return workspace_dir(ava._boot.agent_id()) / _OVERFLOW_DIRNAME


def wrap_code_output(
    output: str,
    *,
    cancelled: bool = False,
    timed_out: bool = False,
    timeout_seconds: float | None = None,
    max_chars: int | None = None,
    stream_cap: StreamCap | None = None,
    referenced_messages: Sequence[BaseMessage] = (),
) -> str:
    """Generate the code execution output envelope fed to the LLM.

    `output` is the exec's stdout + stderr merged stream (both
    redirected to the same `StreamingTextIO`) — preserves the real
    chronological order of print / traceback / log output, same as
    running Python in a terminal.

    When cancelled=True, adds a [cancelled by user] marker — the agent sees
    it was interrupted and can handle gracefully next turn.

    timeout_seconds / max_chars default to settings.sandbox.exec_timeout_seconds /
    settings.sandbox.exec_output_max_chars. Explicit params let tests override.

    `stream_cap` is set when the accumulation cap already dropped the middle of
    `output` mid-run: it carries the true produced length for the
    instrumentation log line, and tells the overflow archive to stop claiming
    it holds the full text.

    `referenced_messages` is the native node's current context, passed explicitly
    because the parent does not install that state into the child SDK's slot.
    Soft-crop archives mentioned there cannot be evicted to make space.

    Format (double \n after header, same contract as wrap_inbound; the
    frontend splitEnvelope uses this to split header / body):

        Code execution output:

        <output>
        (no output)          # only when output is empty — explicitly tells the agent code ran but produced no output
    """
    if timeout_seconds is None:
        timeout_seconds = settings.sandbox.exec_timeout_seconds
    if max_chars is None:
        max_chars = settings.sandbox.exec_output_max_chars
    # cancelled and timed_out are mutually exclusive — the subprocess result
    # constructor guarantees only one is set. Assert is defense-in-depth: if a future caller
    # forgets the mutual exclusion, this blows up rather than silently emitting two markers.
    assert not (cancelled and timed_out), "cancelled and timed_out are mutually exclusive"  # noqa: S101
    if cancelled:
        marker = f" {EXEC_CANCEL_NOTE}"
    elif timed_out:
        marker = f" [timeout after {timeout_seconds:.0f}s]"
    else:
        marker = ""
    ts = f" {now_timestamp()}" if settings.general.message_timestamps else ""
    header = f"Code execution output{marker}{ts}:"
    if not output:
        body = "(no output)"
    else:
        # Log the true (pre-truncation) length on every exec — instrumentation
        # for tuning max_chars from a real distribution (the stored output is
        # capped, so length can't be recovered from history afterwards). When
        # the accumulation cap fired, `len(output)` is already the capped
        # length; the StreamCap carries what the code actually produced.
        produced = stream_cap.produced_chars if stream_cap is not None else len(output)
        logger.info("[exec output chars] {n}", n=produced)
        preview = None
        crop_after = settings.sandbox.exec_output_crop_after_lines
        if stream_cap is None and crop_after and len(output.splitlines()) > crop_after:
            preview = crop_output(
                output,
                _overflow_dir(),
                settings.sandbox,
                referenced_messages=referenced_messages,
                max_chars=max_chars,
            )
        if preview is not None:
            output = preview
        elif len(output) > max_chars:
            output = truncate_both_ends(output, max_chars, stream_cap=stream_cap)
        body = output if output.endswith("\n") else output + "\n"
    if timed_out:
        # The envelope is the agent's only cue to change strategy — the better
        # primitives must be named here, where the timeout is actually seen.
        body += (
            "\n[hint: this budget is for quick work. Run a long shell command "
            "with ava.shell.run_background (delivers a completion message), or "
            "long Python code as ava.watcher.launch; drive interactive programs "
            "in ava.shell.sessions.]\n"
        )
    return header + "\n\n" + body


def truncate_both_ends(output: str, max_chars: int, *, stream_cap: StreamCap | None = None) -> str:
    """Keep the first + last `max_chars // 2` chars (head carries an overview /
    a help() listing, tail carries the result / traceback), drop the middle,
    and write the archived text to a file the agent can read or grep.

    With `stream_cap` set, `output` is itself the accumulation-capped text: the
    archive holds only what survived that first cap, so the banner says exactly
    that instead of promising the full output.

    Public because the ava_code plugin reuses the same truncate-and-archive
    logic for oversized context files (AGENTS.md / CLAUDE.md) — the user
    ruling (2026-08-11) prescribes the exec-output overflow shape for any
    content too large to fully inject: inline head+tail + archive path."""
    half = max_chars // 2
    head, tail = output[:half], output[-half:]
    omitted = len(output) - 2 * half
    path = _write_overflow_file(output, stream_cap=stream_cap)
    if stream_cap is None:
        total = f"{len(output):,} chars total"
        source = f"full output at {path}"
    else:
        total = (
            f"{stream_cap.produced_chars:,} chars produced, capped to "
            f"{stream_cap.budget_chars:,} during execution — the dropped middle "
            f"is unrecoverable"
        )
        source = f"surviving output at {path}"
    banner = (
        f"[output truncated: {total}; {source} "
        f"(read or grep it); showing first {half:,} + last {half:,} chars]"
    )
    mid = f"\n\n[... {omitted:,} chars omitted — {source} ...]\n\n"
    return banner + "\n\n" + head + mid + tail


def _write_overflow_file(output: str, *, stream_cap: StreamCap | None = None) -> Path:
    """Write `output` to a timestamped file under the workspace overflow dir,
    prune old ones, and return its path.

    A `stream_cap` means the text was already truncated at accumulation time,
    so the file gets a header saying it is not the full output — the agent
    grepping it must not read a miss as "the string was never printed".

    The workspace is per-agent, so no agent-id prefix is needed; the
    microsecond timestamp makes names sortable by exec time and unique within
    an agent (execs are serial, and two in the same microsecond cannot happen).
    """
    d = _overflow_dir()
    d.mkdir(parents=True, exist_ok=True)
    # Stamped in the configured timezone so filenames sort together with the
    # envelope timestamps the agent sees.
    now = datetime.now(ZoneInfo(settings.general.timezone))
    path = d / f"exec_{now.strftime('%Y%m%d_%H%M%S_%f')}.txt"
    if stream_cap is not None:
        output = (
            f"[archive note: {stream_cap.produced_chars:,} chars were produced; the "
            f"{stream_cap.budget_chars:,}-char accumulation budget kept the first + last "
            f"halves and dropped the middle DURING execution — this file is NOT the "
            f"full output]\n\n"
        ) + output
    path.write_text(output, encoding="utf-8")
    existing = sorted(d.glob("exec_*.txt"), key=lambda p: p.stat().st_mtime)
    for old in existing[:-_OVERFLOW_KEEP]:
        old.unlink(missing_ok=True)
    return path
