"""A package's own tests type-check with the tests standard, wherever they sit.

pyright configures by directory: an `executionEnvironments` entry names a root
directory (no globs) and the first entry, in list order, whose root contains a
file decides that file's rules. Tests used to live under `tests/<area>/`, where the
ladder holds them to the two call-signature rules at `error` and the other five
`reportUnknown*`/`reportMissing*` rules at `warning` (tests are monkeypatch-stub
code; the header of `[tool.pyright]` measures why). A test moved into
`base/**/tests/`, `ops/**/tests/` or `services/**/tests/` would fall under that
package's environment instead, which holds production code to all seven rules at
`error`; one moved into `ava/`, `scripts/` or `ava_builtins/` would fall to the
global `warning` and drop the two gated rules. Nothing reports either: pyright
just stops applying the standard. So each such directory needs its own entry,
listed above its package's. Those entries are generated by
`scripts/codegen/gen_pyright_test_environments.py` into a fenced region of
pyproject.toml; this test says which directory is missing one, and the tests at the
end pin the generator.

Measured on 18 real test files copied into `base/`, `services/` and `ops/` test
directories (pyright on those files only): 0 errors / 41 warnings before the copy,
22 errors / 19 warnings after, every one of the 22 a warning promoted by the
package's environment.
"""

from __future__ import annotations

import subprocess
import tomllib
from pathlib import Path
from typing import Any

import pytest

from scripts.codegen import gen_pyright_test_environments as gen
from scripts.codegen.gen_pyright_test_environments import (
    CALL_SIGNATURE_RULES,
    HOSTS,
    TESTS_STANDARD,
    effective_rules,
)

_REPO_ROOT = Path(__file__).resolve().parents[2]
_PYRIGHT = tomllib.loads((_REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))["tool"][
    "pyright"
]


def _config(*environments: dict[str, Any]) -> dict[str, Any]:
    return {**dict.fromkeys(TESTS_STANDARD, "warning"), "executionEnvironments": list(environments)}


_STRICT_ROOT = {"root": "base", **dict.fromkeys(TESTS_STANDARD, "error")}
_TESTS_ENV = {"root": "base/packages/tests", **dict.fromkeys(CALL_SIGNATURE_RULES, "error")}


def test_a_tests_directory_under_a_strict_package_is_held_to_the_package_rules() -> None:
    rules = effective_rules(_config(_STRICT_ROOT), "base/packages/tests")
    assert rules != TESTS_STANDARD
    assert set(rules.values()) == {"error"}


def test_its_own_entry_above_the_package_entry_restores_the_standard() -> None:
    config = _config(_TESTS_ENV, _STRICT_ROOT)
    assert effective_rules(config, "base/packages/tests") == TESTS_STANDARD
    # A subdirectory of the tests directory follows the same entry.
    assert effective_rules(config, "base/packages/tests/fixtures") == TESTS_STANDARD
    # Production code beside it keeps the package rules.
    assert set(effective_rules(config, "base/packages").values()) == {"error"}


def test_an_entry_listed_after_the_package_entry_never_applies() -> None:
    assert effective_rules(_config(_STRICT_ROOT, _TESTS_ENV), "base/packages/tests") != (
        TESTS_STANDARD
    )


def test_a_tests_directory_under_a_package_without_an_entry_falls_to_the_global_rules() -> None:
    """`ava/`, `scripts/` and `ava_builtins/` have no environment: the two gated rules are lost."""
    rules = effective_rules(_config(_STRICT_ROOT), "ava/tests")
    assert set(rules.values()) == {"warning"}


def test_a_package_environment_that_matches_the_standard_needs_no_entry() -> None:
    """`cli/`, `gateway/` and `agent/` already gate exactly the two call-signature rules."""
    config = _config({"root": "cli", **dict.fromkeys(CALL_SIGNATURE_RULES, "error")})
    assert effective_rules(config, "cli/commands/tests") == TESTS_STANDARD


def _tracked_test_directories() -> list[str]:
    result = subprocess.run(  # noqa: S603 - fixed git query in this repository
        ["git", "-C", str(_REPO_ROOT), "ls-files", "-z", "--", "*.py"],
        capture_output=True,
        text=True,
        check=True,
    )
    directories = {
        path.rsplit("/", 1)[0]
        for path in result.stdout.split("\0")
        if path.split("/")[0] in HOSTS and "tests" in path.split("/")[:-1]
    }
    return sorted(directories)


def test_every_package_tests_directory_is_held_to_the_tests_standard() -> None:
    wrong = {
        directory: effective_rules(_PYRIGHT, directory)
        for directory in _tracked_test_directories()
        if effective_rules(_PYRIGHT, directory) != TESTS_STANDARD
    }
    assert not wrong, (
        "these test directories are not type-checked to the tests standard "
        f"({dict(TESTS_STANDARD)}): {sorted(wrong)}. The entries are generated: run "
        "`.venv/bin/python scripts/codegen/gen_pyright_test_environments.py`."
    )


def test_the_real_configuration_names_all_seven_rules_globally() -> None:
    assert all(rule in _PYRIGHT for rule in TESTS_STANDARD)


@pytest.mark.parametrize("environment", _PYRIGHT["executionEnvironments"])
def test_an_environment_root_that_exists_names_a_directory(environment: dict[str, Any]) -> None:
    """A stale root (a directory that moved or was deleted) configures nothing."""
    assert (_REPO_ROOT / environment["root"]).is_dir(), environment["root"]


# ── the generator ───────────────────────────────────────────────────────────

_SYNTHETIC_PYPROJECT = f"""\
[tool.pyright]
{chr(10).join(f'{rule} = "warning"' for rule in TESTS_STANDARD)}

# Hand-written before the generated region.
[[tool.pyright.executionEnvironments]]
root = "tests/e2e"
reportUnknownMemberType = "error"
reportUnknownArgumentType = "error"

{gen.BEGIN}
{gen.END}

# Hand-written after the generated region.
[[tool.pyright.executionEnvironments]]
root = "base"
{chr(10).join(f'{rule} = "error"' for rule in TESTS_STANDARD)}

[[tool.pyright.executionEnvironments]]
root = "cli"
reportUnknownMemberType = "error"
reportUnknownArgumentType = "error"

[[tool.pyright.executionEnvironments]]
root = "ava_builtins/skills/web-ai"
extraPaths = ["ava_builtins/skills/web-ai/scripts"]
"""


def _without_region(text: str) -> str:
    return text[: text.index(gen.BEGIN)] + text[text.index(gen.END) :]


def _generated_roots(text: str) -> list[str]:
    region = text[text.index(gen.BEGIN) : text.index(gen.END)]
    return [line.split('"')[1] for line in region.splitlines() if line.startswith("root = ")]


def test_tests_roots_are_the_outermost_tests_directory_of_a_package_module() -> None:
    assert gen.tests_roots(
        [
            "base/packages/tests/test_a.py",
            "base/packages/tests/area/test_b.py",  # same root
            "base/packages/tests/tests/test_c.py",  # a tests/ inside tests/ is not a new root
            "ava_builtins/skills/gmail/scripts/tests/test_gmail.py",
            "tests/base/test_top.py",  # the top-level tests/ is hand-listed
            "docs/tests/test_x.py",  # not a package host
            "base/packages/attests/x.py",
            "base/packages/mod.py",
        ]
    ) == ["ava_builtins/skills/gmail/scripts/tests", "base/packages/tests"]


def test_an_entry_is_written_only_where_the_package_rules_differ_from_the_standard() -> None:
    tracked = [
        "base/x/tests/test_a.py",  # base is strict: needs an entry
        "cli/y/tests/test_b.py",  # cli already gates the two rules: none
        "ava/z/tests/test_c.py",  # no environment, global warning: needs one
        "ava_builtins/skills/web-ai/scripts/tests/test_w.py",  # repeats the extraPaths
    ]
    text = gen.generate(_SYNTHETIC_PYPROJECT, tracked)
    assert _generated_roots(text) == [
        "ava/z/tests",
        "ava_builtins/skills/web-ai/scripts/tests",
        "base/x/tests",
    ]
    region = text[text.index(gen.BEGIN) : text.index(gen.END)]
    assert (
        'root = "ava_builtins/skills/web-ai/scripts/tests"\n'
        'extraPaths = ["ava_builtins/skills/web-ai/scripts"]\n'
        'reportUnknownMemberType = "error"\n'
        'reportUnknownArgumentType = "error"\n\n'
    ) in region
    # Every directory the generator was told about is now held to the standard, its package is not.
    config = tomllib.loads(text)["tool"]["pyright"]
    for root in [*_generated_roots(text), "cli/y/tests"]:
        assert effective_rules(config, root) == TESTS_STANDARD, root
    assert set(effective_rules(config, "base/x").values()) == {"error"}
    assert config["executionEnvironments"][1]["root"] == "ava/z/tests"  # above `base`


def test_generating_twice_changes_nothing_and_the_output_is_sorted() -> None:
    tracked = ["services/b/tests/test_a.py", "base/x/tests/test_a.py", "ava/a/tests/test_a.py"]
    once = gen.generate(_SYNTHETIC_PYPROJECT, tracked)
    assert gen.generate(once, tracked) == once
    assert gen.generate(once, list(reversed(tracked))) == once
    roots = _generated_roots(once)
    assert roots == sorted(roots)


def test_a_region_marker_that_is_missing_or_repeated_stops_the_generator() -> None:
    with pytest.raises(SystemExit, match="exactly one generated region"):
        gen.generate(_SYNTHETIC_PYPROJECT.replace(gen.END, ""), [])
    with pytest.raises(SystemExit, match="exactly one generated region"):
        gen.generate(_SYNTHETIC_PYPROJECT + gen.BEGIN + "\n" + gen.END + "\n", [])
    with pytest.raises(SystemExit, match="out of order"):
        swapped = _SYNTHETIC_PYPROJECT.replace(gen.BEGIN, "@@").replace(gen.END, gen.BEGIN)
        gen.generate(swapped.replace("@@", gen.END), [])


class _Checkout:
    """A scratch git repository holding the synthetic pyproject.toml and its tests modules."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.pyproject = root / "pyproject.toml"
        self._git("init", "-q")
        self.pyproject.write_text(_SYNTHETIC_PYPROJECT, encoding="utf-8")

    def _git(self, *args: str) -> None:
        subprocess.run(["git", "-C", str(self.root), *args], check=True, capture_output=True)  # noqa: S603

    def add(self, rel: str) -> None:
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("def test_x() -> None:\n    pass\n", encoding="utf-8")
        self._git("add", rel)

    def remove(self, rel: str) -> None:
        self._git("rm", "-q", "-f", rel)

    def check(self) -> int:
        return gen.main(["--check"], repo_root=self.root)

    def regenerate(self) -> int:
        return gen.main([], repo_root=self.root)

    def roots(self) -> list[str]:
        return _generated_roots(self.pyproject.read_text())


@pytest.fixture
def checkout(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> _Checkout:
    for name in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR"):
        monkeypatch.delenv(name, raising=False)
    return _Checkout(tmp_path)


def test_moving_a_tests_directory_makes_the_check_fail_until_the_generator_runs(
    checkout: _Checkout,
) -> None:
    checkout.add("base/pkg/tests/test_a.py")
    assert checkout.check() == 1  # nothing generated yet
    assert checkout.regenerate() == 0
    assert checkout.check() == 0
    assert checkout.roots() == ["base/pkg/tests"]

    # A test moves into another package: the region is stale until the script runs.
    checkout.add("services/example/tests/test_b.py")
    assert checkout.check() == 1
    assert checkout.roots() == ["base/pkg/tests"]  # --check writes nothing
    assert checkout.regenerate() == 0
    assert checkout.check() == 0
    assert checkout.roots() == ["base/pkg/tests", "services/example/tests"]


def test_the_generator_changes_nothing_outside_the_fenced_region(checkout: _Checkout) -> None:
    handwritten = _without_region(checkout.pyproject.read_text())
    checkout.add("base/pkg/tests/test_a.py")
    checkout.add("ava/sdk/tests/test_b.py")
    assert checkout.regenerate() == 0
    assert _without_region(checkout.pyproject.read_text()) == handwritten


def test_a_pure_deletion_makes_the_region_stale_too(checkout: _Checkout) -> None:
    """The case a `files:`-filtered pre-commit hook never sees, hence the pre-push family."""
    checkout.add("base/pkg/tests/test_a.py")
    checkout.add("services/example/tests/test_b.py")
    assert checkout.regenerate() == 0
    checkout.remove("services/example/tests/test_b.py")
    assert checkout.check() == 1
    assert checkout.regenerate() == 0
    assert checkout.roots() == ["base/pkg/tests"]
