"""Exercise hooks as processes without touching the developer's shared hooks."""

# ruff: noqa: S603 — subprocess commands use only test-owned paths and fixture literals.

import fcntl
import os
import selectors
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Literal

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[2]
GUARD = ROOT / "scripts/prepush-guard.sh"
CHECK = ROOT / "scripts/provision/check_git_hooks.py"
INSTALL = ".venv/bin/pre-commit install --hook-type pre-commit --hook-type pre-push"
requires_flock = pytest.mark.skipif(shutil.which("flock") is None, reason="flock is not installed")


@pytest.fixture
def checkout(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    # Clear hook context before even initializing the temporary repository.
    for name in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR"):
        monkeypatch.delenv(name, raising=False)
    repo = tmp_path / "main clone"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", str(repo)], check=True)
    monkeypatch.setenv("AVA_PREPUSH_LOCK_DIR", str(tmp_path / "locks"))
    monkeypatch.setenv("AVA_PREPUSH_MAX_LOAD_PER_CORE", "1000000")
    monkeypatch.setenv("AVA_PREPUSH_LOCK_WAIT_SECONDS", "2")
    executable = repo / ".venv/bin/pyright"
    executable.parent.mkdir(parents=True)
    executable.symlink_to(sys.executable)
    return repo


def run_guard(
    repo: Path, tool: str = "pyright", code: str = "print('executed')"
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(GUARD), tool, "--", sys.executable, "-c", code],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
        timeout=10,
    )


def check_install(repo: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CHECK)],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
        timeout=1,
    )


def install_fixture(repo: Path, interpreter: Path | None = None) -> Path:
    if interpreter is None:
        interpreter = repo / ".venv/bin/python"
        interpreter.symlink_to(sys.executable)
    for hook_type in ("pre-commit", "pre-push"):
        hook = repo / ".git/hooks" / hook_type
        hook.write_text(
            "#!/usr/bin/env bash\n"
            "# File generated by pre-commit: https://pre-commit.com\n"
            "# ID: 138fd403232d2ddd5efb44317e38bf03\n"
            f"INSTALL_PYTHON={shlex.quote(str(interpreter))}\n"
            f"ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type={hook_type})\n"
        )
        hook.chmod(0o755)
    return repo / ".git/hooks/pre-push"


def test_stage_contract() -> None:
    config = yaml.safe_load((ROOT / ".pre-commit-config.yaml").read_text())
    assert config["default_install_hook_types"] == ["pre-commit", "pre-push"]
    hooks = {hook["id"]: hook for repo in config["repos"] for hook in repo["hooks"]}
    for name in ("pyright", "frontend-tsc", "frontend-eslint", "frontend-vitest"):
        hook = hooks[name]
        assert hook["stages"] == ["pre-push"]
        assert hook["verbose"] is True  # pre-commit hides output on PASS otherwise.
        assert "bash scripts/prepush-guard.sh " in hook["entry"]
    vitest = hooks["frontend-vitest"]
    assert vitest["entry"] == (
        "bash scripts/prepush-guard.sh vitest -- bash -c 'cd ui/web && npx --no-install vitest run'"
    )
    assert vitest["files"] == r"^ui/web/.*\.(ts|tsx)$"
    assert vitest["pass_filenames"] is False
    check = hooks["check-git-hooks-install"]
    assert check["stages"] == ["pre-commit"]
    assert check["always_run"] is True
    assert check["verbose"] is True


def test_missing_flock_skips(checkout: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    shim_dir = checkout / "no-flock"
    shim_dir.mkdir()
    bash = shutil.which("bash")
    assert bash is not None
    (shim_dir / "bash").symlink_to(bash)
    monkeypatch.setenv("PATH", str(shim_dir))
    marker = checkout / "executed"
    result = run_guard(checkout, code=f"from pathlib import Path; Path({str(marker)!r}).touch()")
    assert result.returncode == 0
    assert "PRE-PUSH SKIPPED [pyright]: flock is not installed" in result.stderr
    assert not marker.exists()


@requires_flock
def test_load_skip(checkout: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    # Fix the measured load in the probe, then force its threshold via env.
    probe_dir = checkout / "probe"
    probe_dir.mkdir()
    probe = probe_dir / "python3"
    probe.write_text(
        f"#!{sys.executable}\nimport os, sys\n"
        "os.getloadavg = lambda: (100.0, 0.0, 0.0)\nsys.argv = sys.argv[1:]\nexec(sys.stdin.read())\n"
    )
    probe.chmod(0o755)
    monkeypatch.setenv("PATH", str(probe_dir) + os.pathsep + os.environ["PATH"])
    monkeypatch.setenv("AVA_PREPUSH_MAX_LOAD_PER_CORE", "0")
    result = run_guard(checkout)
    assert result.returncode == 0
    assert "PRE-PUSH SKIPPED [pyright]" in result.stderr
    assert "load/core" in result.stderr and "threshold 0" in result.stderr
    assert "executed" not in result.stdout


@requires_flock
def test_lock_wait_proceeds(checkout: Path, tmp_path: Path) -> None:
    lock_dir = tmp_path / "locks"
    lock_dir.mkdir()
    with (lock_dir / "pyright.lock").open("w") as held:
        fcntl.flock(held, fcntl.LOCK_EX)
        with subprocess.Popen(
            ["bash", str(GUARD), "pyright", "--", sys.executable, "-c", "print('executed')"],
            cwd=checkout,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        ) as process:
            try:
                assert process.stderr is not None
                with selectors.DefaultSelector() as selector:
                    selector.register(process.stderr, selectors.EVENT_READ)
                    assert selector.select(timeout=5), "wrapper never reported lock contention"
                assert "waiting for pyright lock" in process.stderr.readline()
                assert process.poll() is None
                fcntl.flock(held, fcntl.LOCK_UN)
                stdout, stderr = process.communicate(timeout=5)
                assert process.returncode == 0
                assert "executed" in stdout and "SKIPPED" not in stderr
            finally:
                if process.poll() is None:
                    process.kill()
                    process.wait(timeout=5)


@requires_flock
def test_lock_timeout(checkout: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AVA_PREPUSH_LOCK_WAIT_SECONDS", "0.01")
    lock_dir = tmp_path / "locks"
    lock_dir.mkdir()
    with (lock_dir / "pyright.lock").open("w") as held:
        fcntl.flock(held, fcntl.LOCK_EX)
        result = run_guard(checkout)
    assert result.returncode == 0
    assert "waiting for pyright lock" in result.stderr
    assert "PRE-PUSH SKIPPED [pyright]: lock wait timed out after 0.01s" in result.stderr
    assert "executed" not in result.stdout


@pytest.mark.parametrize("tool", ["tsc", "eslint", "vitest"])
@requires_flock
def test_missing_frontend_env(checkout: Path, tool: str) -> None:
    result = run_guard(checkout, tool)
    assert result.returncode == 0
    assert f"PRE-PUSH SKIPPED [{tool}]: missing ui/web/node_modules" in result.stderr
    assert "npm ci" in result.stderr
    assert "executed" not in result.stdout


@pytest.mark.parametrize("status", [0, 1, 7])
@requires_flock
def test_vitest_binary_and_command_status(
    checkout: Path, monkeypatch: pytest.MonkeyPatch, status: int
) -> None:
    bins = checkout / "ui/web/node_modules/.bin"
    bins.mkdir(parents=True)
    for name in ("node", "npm"):
        (bins / name).symlink_to(sys.executable)
    monkeypatch.setenv("PATH", str(bins) + os.pathsep + os.environ["PATH"])
    missing = run_guard(checkout, "vitest")
    assert missing.returncode == 0
    assert "missing frontend executable vitest" in missing.stderr
    assert "executed" not in missing.stdout

    (bins / "vitest").symlink_to(sys.executable)
    result = run_guard(checkout, "vitest", code=f"print('executed'); raise SystemExit({status})")
    assert result.returncode == status
    assert "executed" in result.stdout
    assert "SKIPPED" not in result.stderr


@requires_flock
def test_missing_python_env(checkout: Path) -> None:
    (checkout / ".venv/bin/pyright").unlink()
    result = run_guard(checkout)
    assert result.returncode == 0
    assert "missing .venv/bin/pyright" in result.stderr
    assert "executed" not in result.stdout


@pytest.mark.parametrize("status", [0, 1, 7])
@requires_flock
def test_real_command_status_propagates(checkout: Path, status: int) -> None:
    result = run_guard(checkout, code=f"print('executed'); raise SystemExit({status})")
    assert result.returncode == status
    assert "executed" in result.stdout
    assert "SKIPPED" not in result.stderr


def test_missing_hook_warns(checkout: Path) -> None:
    result = check_install(checkout)
    assert result.returncode == 0
    assert "WARNING: missing" in result.stdout and INSTALL in result.stdout
    assert ".git/hooks/pre-commit" in result.stdout
    assert ".git/hooks/pre-push" in result.stdout


@pytest.mark.parametrize("problem", ["ephemeral", "dot-worktrees", "wrong-stage", "malformed"])
def test_precommit_drift_reports_both_hooks(checkout: Path, tmp_path: Path, problem: str) -> None:
    push_hook = install_fixture(checkout)
    commit_hook = checkout / ".git/hooks/pre-commit"
    source = commit_hook.read_text()
    if problem in ("ephemeral", "dot-worktrees"):
        directory = "worktrees" if problem == "ephemeral" else ".worktrees"
        ephemeral = tmp_path / directory / "task/.venv/bin/python"
        ephemeral.parent.mkdir(parents=True)
        ephemeral.symlink_to(sys.executable)
        source = source.replace(
            shlex.quote(str(checkout / ".venv/bin/python")), shlex.quote(str(ephemeral))
        )
    elif problem == "wrong-stage":
        source = source.replace("--hook-type=pre-commit", "--hook-type=pre-push")
    else:
        source = source.replace("INSTALL_PYTHON=", "INSTALL_PYTHON='")
    commit_hook.write_text(source)
    push_hook.chmod(0o644)
    result = check_install(checkout)
    assert result.returncode == 0
    assert str(commit_hook) in result.stdout and str(push_hook) in result.stdout
    assert result.stdout.count("WARNING:") == 2
    assert INSTALL in result.stdout


def test_valid_hook_silent_in_main_and_linked_worktree(checkout: Path, tmp_path: Path) -> None:
    install_fixture(checkout)
    subprocess.run(
        [
            "git",
            "-c",
            "user.name=Test",
            "-c",
            "user.email=test@example.com",
            "commit",
            "--allow-empty",
            "-qm",
            "fixture",
        ],
        cwd=checkout,
        check=True,
    )
    worktree = tmp_path / "linked"
    subprocess.run(
        ["git", "worktree", "add", "-qb", "linked", str(worktree)], cwd=checkout, check=True
    )
    for repo in (checkout, worktree):
        result = check_install(repo)
        assert result.returncode == 0 and result.stdout == result.stderr == ""


@pytest.mark.parametrize(
    "problem", ["unmanaged", "dead", "ephemeral", "nonexecutable", "malformed", "override"]
)
def test_broken_install_warns(
    checkout: Path,
    tmp_path: Path,
    problem: Literal["unmanaged", "dead", "ephemeral", "nonexecutable", "malformed", "override"],
) -> None:
    hook = install_fixture(checkout)
    match problem:
        case "unmanaged":
            hook.write_text("#!/bin/sh\nexit 0\n")
        case "dead":
            (checkout / ".venv/bin/python").unlink()
        case "ephemeral":
            ephemeral = tmp_path / "worktrees/task/.venv/bin/python"
            ephemeral.parent.mkdir(parents=True)
            ephemeral.symlink_to(sys.executable)
            install_fixture(checkout, ephemeral)
        case "nonexecutable":
            hook.chmod(0o644)
        case "malformed":
            hook.write_text(hook.read_text().replace("INSTALL_PYTHON=", "INSTALL_PYTHON='"))
        case "override":
            subprocess.run(
                ["git", "config", "core.hooksPath", ".custom-hooks"], cwd=checkout, check=True
            )
    result = check_install(checkout)
    assert result.returncode == 0
    assert "WARNING:" in result.stdout and INSTALL in result.stdout


def test_worktree_setup_does_not_reinstall_shared_hooks() -> None:
    script = (ROOT / "scripts/setup-worktree.sh").read_text()
    assert "pre-commit install" not in script
    assert "git config" not in script
    assert "provision/check_git_hooks.py" in script


def test_stable_uv_tool_interpreter_is_silent(checkout: Path, tmp_path: Path) -> None:
    interpreter = tmp_path / ".local/share/uv/tools/pre-commit/bin/python"
    interpreter.parent.mkdir(parents=True)
    interpreter.symlink_to(sys.executable)
    install_fixture(checkout, interpreter)
    result = check_install(checkout)
    assert result.returncode == 0 and result.stdout == result.stderr == ""
