"""Exercise hooks as processes without touching the developer's shared hooks."""

# ruff: noqa: S603 — subprocess commands use only test-owned paths and fixture literals.

import fcntl
import os
import re
import selectors
import shlex
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Literal

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[2]
GUARD = ROOT / "scripts/prepush-guard.sh"
CHECK = ROOT / "scripts/provision/check_git_hooks.py"
BRANCH_LINT = ROOT / "scripts/prepush-branch-lint.sh"
ARTIFACT_FRESHNESS = ROOT / "scripts/prepush-artifact-freshness.sh"
INSTALL = ".venv/bin/pre-commit install --hook-type pre-commit --hook-type pre-push"
requires_flock = pytest.mark.skipif(shutil.which("flock") is None, reason="flock is not installed")


@pytest.fixture
def checkout(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    # Clear hook context before even initializing the temporary repository.
    for name in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR"):
        monkeypatch.delenv(name, raising=False)
    repo = tmp_path / "main clone"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", str(repo)], check=True)
    monkeypatch.setenv("AVA_PREPUSH_LOCK_DIR", str(tmp_path / "locks"))
    monkeypatch.setenv("AVA_PREPUSH_MAX_LOAD_PER_CORE", "1000000")
    monkeypatch.setenv("AVA_PREPUSH_LOCK_WAIT_SECONDS", "2")
    executable = repo / ".venv/bin/pyright"
    executable.parent.mkdir(parents=True)
    executable.symlink_to(sys.executable)
    return repo


def run_guard(
    repo: Path, tool: str = "pyright", code: str = "print('executed')"
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(GUARD), tool, "--", sys.executable, "-c", code],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
        timeout=10,
    )


def check_install(repo: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CHECK)],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
        timeout=1,
    )


def install_fixture(repo: Path, interpreter: Path | None = None) -> Path:
    if interpreter is None:
        interpreter = repo / ".venv/bin/python"
        interpreter.symlink_to(sys.executable)
    for hook_type in ("pre-commit", "pre-push"):
        hook = repo / ".git/hooks" / hook_type
        hook.write_text(
            "#!/usr/bin/env bash\n"
            "# File generated by pre-commit: https://pre-commit.com\n"
            "# ID: 138fd403232d2ddd5efb44317e38bf03\n"
            f"INSTALL_PYTHON={shlex.quote(str(interpreter))}\n"
            f"ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type={hook_type})\n"
        )
        hook.chmod(0o755)
    return repo / ".git/hooks/pre-push"


def test_stage_contract() -> None:
    config = yaml.safe_load((ROOT / ".pre-commit-config.yaml").read_text())
    assert config["default_install_hook_types"] == ["pre-commit", "pre-push"]
    hooks = {hook["id"]: hook for repo in config["repos"] for hook in repo["hooks"]}
    for name in ("pyright", "frontend-tsc", "frontend-eslint", "frontend-vitest"):
        hook = hooks[name]
        assert hook["stages"] == ["pre-push"]
        assert hook["verbose"] is True  # pre-commit hides output on PASS otherwise.
        assert "bash scripts/prepush-guard.sh " in hook["entry"]
    vitest = hooks["frontend-vitest"]
    assert vitest["entry"] == (
        "bash scripts/prepush-guard.sh vitest -- bash -c 'cd ui/web && npx --no-install vitest run'"
    )
    assert vitest["files"] == r"^ui/web/.*\.(ts|tsx)$"
    assert vitest["pass_filenames"] is False
    check = hooks["check-git-hooks-install"]
    assert check["stages"] == ["pre-commit"]
    assert check["always_run"] is True
    assert check["verbose"] is True


def test_prepush_parity_hooks_configured() -> None:
    # Both close a distinct gap left by pre-commit's own diff selection (see
    # the hooks' comments in .pre-commit-config.yaml): rebase/cherry-pick/merge
    # commits that never ran pre-commit, and a delete-only diff that a
    # files:-filtered hook can never see on any range. Neither may leak into
    # the pre-commit stage -- that would make every `git commit` pay their cost.
    config = yaml.safe_load((ROOT / ".pre-commit-config.yaml").read_text())
    hooks = {hook["id"]: hook for repo in config["repos"] for hook in repo["hooks"]}

    branch_diff = hooks["lint-prepush-branch-diff"]
    assert branch_diff["stages"] == ["pre-push"]
    assert branch_diff["always_run"] is True
    assert branch_diff["verbose"] is True
    assert branch_diff["pass_filenames"] is False
    assert branch_diff["entry"] == "bash scripts/prepush-branch-lint.sh"

    freshness = hooks["lint-prepush-artifact-freshness"]
    assert freshness["stages"] == ["pre-push"]
    assert freshness["always_run"] is True
    assert freshness["verbose"] is True
    assert freshness["pass_filenames"] is False
    assert freshness["entry"] == "bash scripts/prepush-artifact-freshness.sh"


def test_artifact_freshness_hook_list_matches_config() -> None:
    # Drift guard: scripts/prepush-artifact-freshness.sh hardcodes the
    # generated-artifact/snapshot hook family so it can duplicate each one
    # unconditionally at push. A new files:-filtered snapshot hook added to
    # .pre-commit-config.yaml without also joining this list would silently
    # keep the same delete-only blind spot the hook exists to close.
    script = ARTIFACT_FRESHNESS.read_text()
    match = re.search(r"hooks=\(\n(.*?)\n\)\n", script, re.S)
    assert match, "scripts/prepush-artifact-freshness.sh must define a hooks=(...) array"
    listed = [line.strip() for line in match.group(1).splitlines() if line.strip()]
    expected = {
        "lint-contract-snapshots",
        "types-codegen-fresh",
        "constants-codegen-fresh",
        "events-registry-fresh",
        "config-lite-table-fresh",
        "lint-ava-okf",
        "check-doc-references",
    }
    assert len(listed) == len(expected), "duplicate id in prepush-artifact-freshness.sh hooks list"
    assert set(listed) == expected

    config = yaml.safe_load((ROOT / ".pre-commit-config.yaml").read_text())
    hooks = {hook["id"]: hook for repo in config["repos"] for hook in repo["hooks"]}
    for hook_id in listed:
        hook = hooks[hook_id]
        # Each must still be a normal filtered pre-commit-stage hook: the
        # freshness script is what adds the always_run/push-time behavior,
        # not the hook's own commit-time definition.
        assert hook.get("pass_filenames") is False
        assert "pre-commit" in hook.get("stages", config["default_stages"])
        assert hook.get("always_run") is not True


def test_branch_lint_skips_without_origin_main(checkout: Path) -> None:
    result = subprocess.run(
        ["bash", str(BRANCH_LINT)],
        cwd=checkout,
        capture_output=True,
        text=True,
        check=False,
        timeout=10,
    )
    assert result.returncode == 0
    assert "PRE-PUSH SKIPPED [branch-lint]: origin/main is not resolvable locally" in result.stderr


def test_branch_lint_guard_missing_flock_skips(
    checkout: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Same PATH-shimming technique as test_missing_flock_skips below, applied
    # to the new "branch-lint" tool so this passes on any host regardless of
    # whether flock is actually installed here.
    shim_dir = checkout / "no-flock"
    shim_dir.mkdir()
    bash = shutil.which("bash")
    assert bash is not None
    (shim_dir / "bash").symlink_to(bash)
    monkeypatch.setenv("PATH", str(shim_dir))
    result = run_guard(checkout, "branch-lint")
    assert result.returncode == 0
    assert "PRE-PUSH SKIPPED [branch-lint]: flock is not installed" in result.stderr
    assert "executed" not in result.stdout


@requires_flock
def test_branch_lint_guard_preflight_missing_precommit(checkout: Path) -> None:
    # scripts/prepush-branch-lint.sh delegates its lock/load handling to
    # prepush-guard.sh's "branch-lint" tool; exercise that preflight directly
    # the same way the existing pyright/tsc/eslint/vitest tests do. Needs a
    # real flock to get past the earlier check, like the other @requires_flock
    # preflight tests in this file.
    result = run_guard(checkout, "branch-lint")
    assert result.returncode == 0
    assert "PRE-PUSH SKIPPED [branch-lint]: missing .venv/bin/pre-commit" in result.stderr
    assert "executed" not in result.stdout


def _init_probe_repo(path: Path) -> None:
    subprocess.run(["git", "init", "-q", str(path)], check=True)
    subprocess.run(["git", "-C", str(path), "config", "user.email", "t@example.com"], check=True)
    subprocess.run(["git", "-C", str(path), "config", "user.name", "Test"], check=True)


def test_delete_only_diff_skips_filtered_hook_but_always_run_catches_it(tmp_path: Path) -> None:
    """Regression test for the gap behind PR #3658 (`base/agents/api.txt` stale
    after a rebase deleted the module it described): pre-commit's own diff
    selection passes a files:-filtered hook only Added/Copied/Modified/Renamed
    paths -- never a Deleted one, on any compared range -- so only an
    always_run duplicate at push can catch a delete-only diff.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_probe_repo(repo)
    log = tmp_path / "ran.log"
    (repo / ".pre-commit-config.yaml").write_text(
        textwrap.dedent(f"""\
            default_install_hook_types: [pre-commit, pre-push]
            default_stages: [pre-commit]
            repos:
              - repo: local
                hooks:
                  - id: filtered-check
                    name: filtered check (commit stage, files filter)
                    entry: bash -c "echo RAN >> {log}"
                    language: system
                    files: ^foo/.*\\.py$
                    pass_filenames: false
                  - id: filtered-check-prepush
                    name: same check, always_run duplicate at prepush
                    entry: bash -c "echo RAN >> {log}"
                    language: system
                    stages: [pre-push]
                    always_run: true
                    pass_filenames: false
            """)
    )
    (repo / "foo").mkdir()
    (repo / "foo/bar.py").write_text("print(1)\n")
    subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-q", "--no-verify", "-m", "c1"], check=True)
    base_sha = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    ).stdout.strip()
    subprocess.run(["git", "-C", str(repo), "rm", "-q", "foo/bar.py"], check=True)
    subprocess.run(
        ["git", "-C", str(repo), "commit", "-q", "--no-verify", "-m", "c2: delete only"], check=True
    )

    def run_pre_commit(*args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, "-m", "pre_commit", *args],
            cwd=repo,
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )

    # The corrected range still selects nothing for the filtered hook: a
    # delete-only diff is invisible to it regardless of which range is used.
    filtered = run_pre_commit(
        "run",
        "--hook-stage",
        "pre-commit",
        "--from-ref",
        base_sha,
        "--to-ref",
        "HEAD",
        "filtered-check",
    )
    assert filtered.returncode == 0
    assert "no files to check" in filtered.stdout
    assert not log.exists()

    # The always_run duplicate ignores the filter entirely and catches it.
    always_run = run_pre_commit("run", "--hook-stage", "pre-push", "--all-files")
    assert always_run.returncode == 0
    assert "no files to check" not in always_run.stdout
    assert log.read_text().count("RAN") == 1


def test_missing_flock_skips(checkout: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    shim_dir = checkout / "no-flock"
    shim_dir.mkdir()
    bash = shutil.which("bash")
    assert bash is not None
    (shim_dir / "bash").symlink_to(bash)
    monkeypatch.setenv("PATH", str(shim_dir))
    marker = checkout / "executed"
    result = run_guard(checkout, code=f"from pathlib import Path; Path({str(marker)!r}).touch()")
    assert result.returncode == 0
    assert "PRE-PUSH SKIPPED [pyright]: flock is not installed" in result.stderr
    assert not marker.exists()


@requires_flock
def test_load_skip(checkout: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    # Fix the measured load in the probe, then force its threshold via env.
    probe_dir = checkout / "probe"
    probe_dir.mkdir()
    probe = probe_dir / "python3"
    probe.write_text(
        f"#!{sys.executable}\nimport os, sys\n"
        "os.getloadavg = lambda: (100.0, 0.0, 0.0)\nsys.argv = sys.argv[1:]\nexec(sys.stdin.read())\n"
    )
    probe.chmod(0o755)
    monkeypatch.setenv("PATH", str(probe_dir) + os.pathsep + os.environ["PATH"])
    monkeypatch.setenv("AVA_PREPUSH_MAX_LOAD_PER_CORE", "0")
    result = run_guard(checkout)
    assert result.returncode == 0
    assert "PRE-PUSH SKIPPED [pyright]" in result.stderr
    assert "load/core" in result.stderr and "threshold 0" in result.stderr
    assert "executed" not in result.stdout


@requires_flock
def test_lock_wait_proceeds(checkout: Path, tmp_path: Path) -> None:
    lock_dir = tmp_path / "locks"
    lock_dir.mkdir()
    with (lock_dir / "pyright.lock").open("w") as held:
        fcntl.flock(held, fcntl.LOCK_EX)
        with subprocess.Popen(
            ["bash", str(GUARD), "pyright", "--", sys.executable, "-c", "print('executed')"],
            cwd=checkout,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        ) as process:
            try:
                assert process.stderr is not None
                with selectors.DefaultSelector() as selector:
                    selector.register(process.stderr, selectors.EVENT_READ)
                    assert selector.select(timeout=5), "wrapper never reported lock contention"
                assert "waiting for pyright lock" in process.stderr.readline()
                assert process.poll() is None
                fcntl.flock(held, fcntl.LOCK_UN)
                stdout, stderr = process.communicate(timeout=5)
                assert process.returncode == 0
                assert "executed" in stdout and "SKIPPED" not in stderr
            finally:
                if process.poll() is None:
                    process.kill()
                    process.wait(timeout=5)


@requires_flock
def test_lock_timeout(checkout: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AVA_PREPUSH_LOCK_WAIT_SECONDS", "0.01")
    lock_dir = tmp_path / "locks"
    lock_dir.mkdir()
    with (lock_dir / "pyright.lock").open("w") as held:
        fcntl.flock(held, fcntl.LOCK_EX)
        result = run_guard(checkout)
    assert result.returncode == 0
    assert "waiting for pyright lock" in result.stderr
    assert "PRE-PUSH SKIPPED [pyright]: lock wait timed out after 0.01s" in result.stderr
    assert "executed" not in result.stdout


@pytest.mark.parametrize("tool", ["tsc", "eslint", "vitest"])
@requires_flock
def test_missing_frontend_env(checkout: Path, tool: str) -> None:
    result = run_guard(checkout, tool)
    assert result.returncode == 0
    assert f"PRE-PUSH SKIPPED [{tool}]: missing ui/web/node_modules" in result.stderr
    assert "npm ci" in result.stderr
    assert "executed" not in result.stdout


@pytest.mark.parametrize("status", [0, 1, 7])
@requires_flock
def test_vitest_binary_and_command_status(
    checkout: Path, monkeypatch: pytest.MonkeyPatch, status: int
) -> None:
    bins = checkout / "ui/web/node_modules/.bin"
    bins.mkdir(parents=True)
    for name in ("node", "npm"):
        (bins / name).symlink_to(sys.executable)
    monkeypatch.setenv("PATH", str(bins) + os.pathsep + os.environ["PATH"])
    missing = run_guard(checkout, "vitest")
    assert missing.returncode == 0
    assert "missing frontend executable vitest" in missing.stderr
    assert "executed" not in missing.stdout

    (bins / "vitest").symlink_to(sys.executable)
    result = run_guard(checkout, "vitest", code=f"print('executed'); raise SystemExit({status})")
    assert result.returncode == status
    assert "executed" in result.stdout
    assert "SKIPPED" not in result.stderr


@requires_flock
def test_missing_python_env(checkout: Path) -> None:
    (checkout / ".venv/bin/pyright").unlink()
    result = run_guard(checkout)
    assert result.returncode == 0
    assert "missing .venv/bin/pyright" in result.stderr
    assert "executed" not in result.stdout


@pytest.mark.parametrize("status", [0, 1, 7])
@requires_flock
def test_real_command_status_propagates(checkout: Path, status: int) -> None:
    result = run_guard(checkout, code=f"print('executed'); raise SystemExit({status})")
    assert result.returncode == status
    assert "executed" in result.stdout
    assert "SKIPPED" not in result.stderr


def test_missing_hook_warns(checkout: Path) -> None:
    result = check_install(checkout)
    assert result.returncode == 0
    assert "WARNING: missing" in result.stdout and INSTALL in result.stdout
    assert ".git/hooks/pre-commit" in result.stdout
    assert ".git/hooks/pre-push" in result.stdout


@pytest.mark.parametrize("problem", ["ephemeral", "dot-worktrees", "wrong-stage", "malformed"])
def test_precommit_drift_reports_both_hooks(checkout: Path, tmp_path: Path, problem: str) -> None:
    push_hook = install_fixture(checkout)
    commit_hook = checkout / ".git/hooks/pre-commit"
    source = commit_hook.read_text()
    if problem in ("ephemeral", "dot-worktrees"):
        directory = "worktrees" if problem == "ephemeral" else ".worktrees"
        ephemeral = tmp_path / directory / "task/.venv/bin/python"
        ephemeral.parent.mkdir(parents=True)
        ephemeral.symlink_to(sys.executable)
        source = source.replace(
            shlex.quote(str(checkout / ".venv/bin/python")), shlex.quote(str(ephemeral))
        )
    elif problem == "wrong-stage":
        source = source.replace("--hook-type=pre-commit", "--hook-type=pre-push")
    else:
        source = source.replace("INSTALL_PYTHON=", "INSTALL_PYTHON='")
    commit_hook.write_text(source)
    push_hook.chmod(0o644)
    result = check_install(checkout)
    assert result.returncode == 0
    assert str(commit_hook) in result.stdout and str(push_hook) in result.stdout
    assert result.stdout.count("WARNING:") == 2
    assert INSTALL in result.stdout


def test_valid_hook_silent_in_main_and_linked_worktree(checkout: Path, tmp_path: Path) -> None:
    install_fixture(checkout)
    subprocess.run(
        [
            "git",
            "-c",
            "user.name=Test",
            "-c",
            "user.email=test@example.com",
            "commit",
            "--allow-empty",
            "-qm",
            "fixture",
        ],
        cwd=checkout,
        check=True,
    )
    worktree = tmp_path / "linked"
    subprocess.run(
        ["git", "worktree", "add", "-qb", "linked", str(worktree)], cwd=checkout, check=True
    )
    for repo in (checkout, worktree):
        result = check_install(repo)
        assert result.returncode == 0 and result.stdout == result.stderr == ""


@pytest.mark.parametrize(
    "problem", ["unmanaged", "dead", "ephemeral", "nonexecutable", "malformed", "override"]
)
def test_broken_install_warns(
    checkout: Path,
    tmp_path: Path,
    problem: Literal["unmanaged", "dead", "ephemeral", "nonexecutable", "malformed", "override"],
) -> None:
    hook = install_fixture(checkout)
    match problem:
        case "unmanaged":
            hook.write_text("#!/bin/sh\nexit 0\n")
        case "dead":
            (checkout / ".venv/bin/python").unlink()
        case "ephemeral":
            ephemeral = tmp_path / "worktrees/task/.venv/bin/python"
            ephemeral.parent.mkdir(parents=True)
            ephemeral.symlink_to(sys.executable)
            install_fixture(checkout, ephemeral)
        case "nonexecutable":
            hook.chmod(0o644)
        case "malformed":
            hook.write_text(hook.read_text().replace("INSTALL_PYTHON=", "INSTALL_PYTHON='"))
        case "override":
            subprocess.run(
                ["git", "config", "core.hooksPath", ".custom-hooks"], cwd=checkout, check=True
            )
    result = check_install(checkout)
    assert result.returncode == 0
    assert "WARNING:" in result.stdout and INSTALL in result.stdout


def test_worktree_setup_does_not_reinstall_shared_hooks() -> None:
    script = (ROOT / "scripts/setup-worktree.sh").read_text()
    assert "pre-commit install" not in script
    assert "git config" not in script
    assert "provision/check_git_hooks.py" in script


def test_stable_uv_tool_interpreter_is_silent(checkout: Path, tmp_path: Path) -> None:
    interpreter = tmp_path / ".local/share/uv/tools/pre-commit/bin/python"
    interpreter.parent.mkdir(parents=True)
    interpreter.symlink_to(sys.executable)
    install_fixture(checkout, interpreter)
    result = check_install(checkout)
    assert result.returncode == 0 and result.stdout == result.stderr == ""


def _init_checkout(path: Path) -> Path:
    path.mkdir(parents=True)
    subprocess.run(["git", "init", "-q", str(path)], check=True)
    interpreter = path / ".venv/bin/python"
    interpreter.parent.mkdir(parents=True)
    interpreter.symlink_to(sys.executable)
    return path


def _scan(home: Path) -> subprocess.CompletedProcess[str]:
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env["HOME"] = str(home)
    return subprocess.run(
        [sys.executable, str(CHECK), "--scan-machine"],
        env=env,
        capture_output=True,
        text=True,
        check=False,
        timeout=10,
    )


def test_machine_scan_clean(tmp_path: Path) -> None:
    home = tmp_path / "home"
    repo = _init_checkout(home / "Ava")
    install_fixture(repo, repo / ".venv/bin/python")
    source = _init_checkout(home / ".ava" / "source")
    install_fixture(source, source / ".venv/bin/python")
    result = _scan(home)
    assert result.returncode == 0
    assert "hook check: OK (2 clone(s))" in result.stdout
    assert "WARNING" not in result.stdout


def test_machine_scan_reports_drifted_checkout(tmp_path: Path) -> None:
    home = tmp_path / "home"
    repo = _init_checkout(home / "Ava")
    install_fixture(repo, repo / ".venv/bin/python")
    drifted = _init_checkout(home / ".ava-preview" / "source")
    interpreter = drifted / ".worktrees" / "wt" / ".venv/bin/python"
    interpreter.parent.mkdir(parents=True)
    interpreter.symlink_to(sys.executable)
    install_fixture(drifted, interpreter)
    result = _scan(home)
    assert result.returncode == 1
    assert "points into a disposable worktree" in result.stdout
    assert "hook check: 2 problem(s) across 2 clone(s)" in result.stdout


def test_machine_scan_reports_missing_hooks(tmp_path: Path) -> None:
    home = tmp_path / "home"
    _init_checkout(home / "Ava")  # hooks dir holds only the samples
    result = _scan(home)
    assert result.returncode == 1
    assert result.stdout.count("missing or non-executable") == 2
    assert "hook check: 2 problem(s) across 1 clone(s)" in result.stdout


def test_machine_scan_dedupes_linked_worktrees(tmp_path: Path) -> None:
    home = tmp_path / "home"
    repo = _init_checkout(home / "Ava")
    install_fixture(repo, repo / ".venv/bin/python")
    subprocess.run(
        [
            "git",
            "-C",
            str(repo),
            "-c",
            "user.email=probe@example.com",
            "-c",
            "user.name=probe",
            "commit",
            "-q",
            "--allow-empty",
            "--no-verify",
            "-m",
            "probe",
        ],
        check=True,
    )
    linked = home / ".ava-linked" / "source"
    linked.parent.mkdir()
    subprocess.run(
        ["git", "-C", str(repo), "worktree", "add", "-q", str(linked), "-b", "probe"],
        check=True,
    )
    result = _scan(home)
    assert result.returncode == 0
    assert "hook check: OK (1 clone(s))" in result.stdout
