CREATE TABLE weixin_ingress_bindings (
    id integer PRIMARY KEY CHECK (id = 1),
    namespace text NOT NULL CHECK (length(namespace) > 0),
    account_id text NOT NULL CHECK (length(account_id) > 0),
    epoch uuid NOT NULL
);

CREATE TABLE weixin_ingress_cursors (
    namespace text NOT NULL CHECK (length(namespace) > 0),
    account_id text NOT NULL CHECK (length(account_id) > 0),
    cursor text NOT NULL,
    state text NOT NULL CHECK (state IN ('held','draining','active')),
    binding_reason text NOT NULL CHECK (binding_reason IN ('unverified_history','legacy_unbound','operator_draining','operator_activated')),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (namespace, account_id)
);

CREATE TABLE weixin_ingress_receipts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace text NOT NULL CHECK (length(namespace) > 0),
    account_id text NOT NULL CHECK (length(account_id) > 0),
    sender_id text NOT NULL CHECK (length(sender_id) > 0),
    message_id text NOT NULL CHECK (message_id ~ '^[1-9][0-9]{0,19}$' AND message_id::numeric < 18446744073709551616),
    request jsonb NOT NULL CHECK (jsonb_typeof(request) = 'object'),
    provider_payload jsonb NOT NULL CHECK (jsonb_typeof(provider_payload) = 'object'),
    route jsonb NOT NULL CHECK (jsonb_typeof(route) = 'object'),
    status text NOT NULL CHECK (status IN ('retained', 'claimed', 'accepted', 'rejected', 'uncertain', 'quarantined')),
    attempt_id uuid,
    inbound_id bigint CHECK (inbound_id > 0),
    outcome_reason text,
    result jsonb CHECK (jsonb_typeof(result) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    UNIQUE (namespace, account_id, sender_id, message_id),
    CHECK (status NOT IN ('claimed','uncertain') OR attempt_id IS NOT NULL),
    CHECK (status <> 'retained' OR (attempt_id IS NULL AND inbound_id IS NULL AND result IS NULL)),
    CHECK (inbound_id IS NULL OR status = 'accepted'),
    CHECK (status <> 'accepted' OR inbound_id IS NOT NULL OR result IS NOT NULL),
    CHECK (status <> 'uncertain' OR outcome_reason IS NOT NULL),
    CHECK (status <> 'quarantined' OR (attempt_id IS NULL AND inbound_id IS NULL AND result IS NULL)),
    CHECK (status NOT IN ('retained','claimed') OR completed_at IS NULL)
);
CREATE INDEX weixin_ingress_pending ON weixin_ingress_receipts(namespace,account_id,id)
    WHERE status IN ('retained','claimed');
