"""Crash-journaled archive and PITR environment application, including the
config-owned gate-key posture enforcement and its operator re-entry guidance."""

from __future__ import annotations

import base64
import hashlib
import json
from collections.abc import Callable
from pathlib import Path

import psycopg
from psycopg import sql

from cli.commands._cluster_instance import pg_admin_url
from services.pitr.activation_runtime import (
    _PITR_ENV_FIELDS,
    _file_evidence,
    pitr_env_absent,
    pitr_env_is_desired,
)
from services.pitr.activation_state import ActivationRecord, load_record, write_record_cas
from shared.cluster import get_record, record_postgres_port
from shared.config import settings
from shared.paths import ava_home


def _pg_connection() -> psycopg.Connection[tuple[object, ...]]:
    cluster = get_record(ava_home())
    if cluster is None:
        raise RuntimeError("cluster registry record is missing")
    return psycopg.connect(pg_admin_url(record_postgres_port(cluster)), autocommit=True)


def _alter(name: str, value: str) -> None:
    """ALTER SYSTEM rejects bound parameters ($1) — the value must ride as a
    quoted literal in the statement text (real PG17, 2026-08-30 activation)."""
    with _pg_connection() as conn:
        conn.execute(
            sql.SQL("ALTER SYSTEM SET {} = {}").format(sql.Identifier(name), sql.Literal(value))
        )


def _auto_conf_entries(home: Path) -> list[tuple[str, str]]:
    """Use PostgreSQL's parser, retaining order and duplicate settings."""
    path = (home / "pg/postgresql.auto.conf").resolve(strict=True)
    with _pg_connection() as conn:
        directory = conn.execute("SHOW data_directory").fetchone()
        if directory is None or Path(str(directory[0])).resolve() != path.parent:
            raise RuntimeError("PostgreSQL configuration connection belongs to another home")
        rows = conn.execute(
            "SELECT name, setting, error FROM pg_file_settings "
            "WHERE sourcefile = %s ORDER BY seqno",
            (str(Path(str(directory[0])) / path.name),),
        ).fetchall()
    # A parsed postmaster setting reports an application error until restart.
    # This reader proves persisted syntax/values, not effective readiness.
    if any(not isinstance(name, str) or not isinstance(value, str) for name, value, _ in rows):
        raise RuntimeError("PostgreSQL auto.conf has unparseable persisted settings")
    return [(str(name), str(value)) for name, value, _error in rows]


def _auto_conf_bytes(entries: list[tuple[str, str]]) -> bytes:
    """Predict PG17's ALTER SYSTEM serializer, never write the file ourselves.

    PostgreSQL guc.c write_auto_conf_file quotes both apostrophes and backslashes;
    replace_auto_config_value removes all named entries and appends a SET value.
    The digest admits only that exact output after an interrupted SQL effect.
    """
    text = "# Do not edit this file manually!\n"
    text += "# It will be overwritten by the ALTER SYSTEM command.\n"
    for name, value in entries:
        escaped = value.replace("\\", "\\\\").replace("'", "''")
        text += f"{name} = '{escaped}'\n"
    return text.encode()


def _persistent_archive_settings(home: Path) -> dict[str, str]:
    entries = dict(_auto_conf_entries(home))
    return {
        name: entries.get(name, "__ABSENT__")
        for name in ("archive_mode", "archive_command", "archive_timeout", "wal_compression")
    }


def _auto_digest(home: Path) -> str:
    return _file_evidence(home / "pg/postgresql.auto.conf")[1]


def _require_owned_auto(home: Path, record: ActivationRecord) -> str:
    expected = record.rollback_expected_auto_conf_digest
    if expected is None or _auto_digest(home) != expected:
        raise RuntimeError("PostgreSQL auto.conf changed outside its last owned digest")
    return expected


def _auto_intent(home: Path, name: str, desired: str, expected: str) -> dict[str, str]:
    entries = _auto_conf_entries(home)
    payload = (home / "pg/postgresql.auto.conf").read_bytes()
    if hashlib.sha256(payload).hexdigest() != expected:
        raise RuntimeError("PostgreSQL auto.conf changed while preparing its intent")
    if payload not in (b"", _auto_conf_bytes(entries)):
        raise RuntimeError("PostgreSQL auto.conf must have its native ALTER SYSTEM format")
    target = [(key, value) for key, value in entries if key.lower() != name.lower()]
    if desired != "__ABSENT__":
        target.append((name, desired))
    return {
        "name": name,
        "expected_digest": expected,
        "desired_digest": hashlib.sha256(_auto_conf_bytes(target)).hexdigest(),
        "desired_value": desired,
    }


def complete_auto_intent(
    home: Path, intent: dict[str, str], alter: Callable[[str, str], None] | None = None
) -> str:
    """Admit only the exact preimage or SQL postimage; effective SHOW is irrelevant."""
    current = _auto_digest(home)
    if current == intent["expected_digest"] and current != intent["desired_digest"]:
        if alter is None:
            return current
        alter(intent["name"], intent["desired_value"])
        current = _auto_digest(home)
    if current != intent["desired_digest"]:
        raise RuntimeError("PostgreSQL auto.conf differs from its exact owned SQL postimage")
    if _persistent_archive_settings(home)[intent["name"]] != intent["desired_value"]:
        raise RuntimeError("PostgreSQL persisted setting differs from its owned SQL intent")
    return current


def _alter_restore(name: str, value: str) -> None:
    with _pg_connection() as conn:
        query = (
            sql.SQL("ALTER SYSTEM RESET {}").format(sql.Identifier(name))
            if value == "__ABSENT__"
            else sql.SQL("ALTER SYSTEM SET {} = {}").format(
                sql.Identifier(name), sql.Literal(value)
            )
        )
        conn.execute(query)


def _journal_rollback(home: Path, record: ActivationRecord, **changes: object) -> ActivationRecord:
    replacement = record.journal_rollback(**changes)
    write_record_cas(home, expected=record, replacement=replacement)
    return replacement


def restore_archive_settings(
    home: Path, record: ActivationRecord, baseline: dict[str, str]
) -> ActivationRecord:
    """Restore persisted settings through exact SQL pre/postimage receipts."""
    from shared.release_operation import require_pitr_authorized

    require_pitr_authorized(home)
    for name, desired in baseline.items():
        applied = dict(record.rollback_settings_applied or {})
        if name in applied:
            if _persistent_archive_settings(home)[name] != desired:
                raise RuntimeError(f"PostgreSQL {name} changed after durable rollback apply")
            continue
        intent = record.rollback_setting_intent
        if intent is None:
            expected = _require_owned_auto(home, record)
            intent = _auto_intent(home, name, desired, expected)
            record = _journal_rollback(home, record, rollback_setting_intent=intent)
        if intent["name"] != name or intent["desired_value"] != desired:
            raise RuntimeError("PostgreSQL setting differs from durable rollback intent")
        digest = complete_auto_intent(home, intent, _alter_restore)
        applied[name] = json.dumps(
            {"desired_value": desired, "post_digest": digest},
            sort_keys=True,
            separators=(",", ":"),
        )
        record = _journal_rollback(
            home,
            record,
            rollback_setting_intent=None,
            rollback_settings_applied=applied,
            rollback_expected_auto_conf_digest=digest,
        )
    _require_owned_auto(home, record)
    return record


def _journal(home: Path, record: ActivationRecord, **changes: object) -> ActivationRecord:
    replacement = record.journal_config(**changes)
    write_record_cas(home, expected=record, replacement=replacement)
    return replacement


def _env_payload(home: Path) -> bytes:
    return (home / ".env").read_bytes()


def apply_wal_config(
    home: Path, record: ActivationRecord, desired: dict[str, str]
) -> ActivationRecord:
    from shared.release_operation import require_pitr_authorized

    require_pitr_authorized(home)
    record = _apply_archive_settings(home, record, desired)

    owned = _apply_env(home, record)
    refreshed = load_record(home)
    if refreshed is None:
        raise RuntimeError("PITR env application lost its business record")
    record = refreshed
    env_digest = hashlib.sha256(owned).hexdigest()
    record = _journal(
        home,
        record,
        config_apply_intent=None,
        config_apply_applied={"kind": "env", "digest": env_digest},
        rollback_expected_env_digest=env_digest,
    )
    replacement = record.advance(
        "wal_restart_pending",
        rollback_expected_auto_conf_digest=_require_owned_auto(home, record),
        error=None,
    )
    write_record_cas(home, expected=record, replacement=replacement)
    return replacement


def _apply_archive_settings(
    home: Path, record: ActivationRecord, desired: dict[str, str]
) -> ActivationRecord:
    intent = record.config_apply_intent
    if intent is not None and intent["kind"] == "env":
        _require_owned_auto(home, record)
        if any(_persistent_archive_settings(home)[key] != value for key, value in desired.items()):
            raise RuntimeError("PostgreSQL persisted settings changed during environment apply")
        return record
    if intent is not None:
        if intent["name"] not in desired or intent["desired_value"] != desired[intent["name"]]:
            raise RuntimeError("PostgreSQL setting differs from durable apply intent")
        record = _finish_archive_intent(home, record, intent)
    for name, value in desired.items():
        expected = _require_owned_auto(home, record)
        if _persistent_archive_settings(home)[name] == value:
            continue
        intent = {"kind": "postgresql_auto_conf", **_auto_intent(home, name, value, expected)}
        record = _journal(home, record, config_apply_intent=intent)
        record = _finish_archive_intent(home, record, intent)
    return record


def _finish_archive_intent(
    home: Path, record: ActivationRecord, intent: dict[str, str]
) -> ActivationRecord:
    digest = complete_auto_intent(home, intent, _alter)
    return _journal(
        home,
        record,
        config_apply_intent=None,
        config_apply_applied={
            "kind": "postgresql_auto_conf",
            "name": intent["name"],
            "digest": digest,
        },
        rollback_expected_auto_conf_digest=digest,
    )


def _apply_env(home: Path, record: ActivationRecord) -> bytes:
    """Append the four absent gate keys in one exact, crash-journaled CAS."""
    from shared.config.candidate import validate_env_patch_for_write
    from shared.envfile import replace_env_bytes_cas

    if record.pre_activation_env_b64 is None or record.pre_activation_env_digest is None:
        raise RuntimeError("PITR env provisioning requires its captured preimage")
    before = base64.b64decode(record.pre_activation_env_b64, validate=True)
    expected = record.pre_activation_env_digest
    if hashlib.sha256(before).hexdigest() != expected:
        raise RuntimeError("PITR env preimage digest differs")
    if pitr_env_is_desired(before):
        target = before
    elif pitr_env_absent(before):
        target = before + (b"" if before.endswith(b"\n") else b"\n")
        target += b"AVA_PITR_ENABLED='true'\nAVA_PITR_BASE_BACKUP_ENABLED='true'\n"
        target += (
            b"AVA_PITR_RESTORE_PROOF_ENABLED='true'\nAVA_PITR_RETENTION_PLANNER_ENABLED='false'\n"
        )
    else:
        raise RuntimeError("PITR gate keys are config-owned; align them before activation")
    desired = hashlib.sha256(target).hexdigest()
    current = hashlib.sha256(_env_payload(home)).hexdigest()
    if current not in {expected, desired}:
        raise RuntimeError(".env differs from the exact PITR preimage and postimage")
    if record.config_apply_intent is None:
        verdict = validate_env_patch_for_write(
            {
                "pitr_enabled": True,
                "pitr_base_backup_enabled": True,
                "pitr_restore_proof_enabled": True,
                "pitr_retention_planner_enabled": False,
            },
            set(),
        )
        if verdict.errors or verdict.expected_digest != current:
            raise RuntimeError("PITR environment candidate is invalid or changed")
        record = _journal(
            home,
            record,
            config_apply_intent={
                "kind": "env",
                "expected_digest": expected,
                "desired_digest": desired,
            },
        )
    if record.config_apply_intent != {
        "kind": "env",
        "expected_digest": expected,
        "desired_digest": desired,
    }:
        raise RuntimeError("PITR environment differs from its recorded byte intent")
    replace_env_bytes_cas(
        home / ".env",
        payload=target,
        expected_digest=expected,
        target_digest=desired,
        audit_site="pitr_activation",
    )
    return target


def gate_unset_command() -> str:
    return "ava config unset " + " ".join(_PITR_ENV_FIELDS)


def require_inactive_gate_posture(boundary: str) -> None:
    """The activation starts from — and freezes its baseline in — the inactive
    posture: every PITR service flag is off. This guard checks the three
    service flags; provisioning at apply time separately needs all four
    config-owned gate keys absent (a present key is never re-provisioned), and
    a rollback never reverts them."""
    config = settings.physical_backup
    enabled = [
        name
        for name, flag in (
            ("pitr_enabled", config.pitr_enabled),
            ("pitr_base_backup_enabled", config.pitr_base_backup_enabled),
            ("pitr_restore_proof_enabled", config.pitr_restore_proof_enabled),
        )
        if flag
    ]
    if not enabled:
        return
    raise RuntimeError(
        f"{boundary} requires all PITR service flags to remain off "
        f"(enabled: {', '.join(enabled)}); unset the four gate keys: "
        f"`{gate_unset_command()}`"
    )


def rollback_gate_hint(home: Path) -> str | None:
    """Rollback never touches the config-owned gate keys; point at the unset
    step when any of the four is still set."""
    env = home / ".env"
    if not env.is_file() or pitr_env_absent(env.read_bytes()):
        return None
    return (
        "PITR gate keys are config-owned and were not reverted by the rollback; "
        f"for a fresh activation unset them with `{gate_unset_command()}`"
    )
