"""Drift locks for the generated boot-lite config index (`base/host/env/config_lite_table.json`).

The index is generated by `scripts/codegen/gen_config_lite_table.py`; its surfaces feed
`base/host/env/registry`'s authority projections and the facade accessors on every
boot path, so any config-field change must regenerate it. These tests fail when
the committed index — or the reader that materializes it — drifts from the live
registry, and they pin the index's outside-the-package location.
"""

from __future__ import annotations

import importlib
import json
import operator
import subprocess
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any, cast

import pytest
from pydantic import ValidationError
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from base.host.env.config_lite_table import (
    FIELD_ALIASES,
    FIELD_CAPABILITIES,
    FIELD_DOMAINS,
    FIELD_SCOPES,
    LITE_FIELDS,
    PER_AGENT_FIELDS,
    REQUIRED_FIELDS,
    SENSITIVE_FIELDS,
)
from base.host.env.config_registry import _build_registry, field_alias, schema_extra

_REPO_ROOT = Path(__file__).resolve().parents[3]
_READER = _REPO_ROOT / "base" / "host" / "env" / "config_lite_table.py"
_INDEX = _REPO_ROOT / "base" / "host" / "env" / "config_lite_table.json"


def test_stall_exit_record_deadline_contract() -> None:
    from base.config.domains.gateway import GatewaySettings

    name = "schedule_stall_exit_record_deadline_seconds"
    alias = "AVA_SCHEDULE_STALL_EXIT_RECORD_DEADLINE_SECONDS"
    info = _build_registry()[name].info
    assert cast(FieldInfo, info).default == 10.0
    assert FIELD_ALIASES[name] == alias
    assert FIELD_DOMAINS[name] == FIELD_CAPABILITIES[name] == "gateway"
    assert FIELD_SCOPES[name] == "cluster-pinned"
    assert schema_extra(info)["restart_required"] == "schedule"
    assert schema_extra(info)["writable"] is True
    configured = GatewaySettings.model_validate({alias: 4.5})
    assert configured.schedule_stall_exit_record_deadline_seconds == 4.5
    for value in (0, -1, float("inf"), float("nan")):
        with pytest.raises(ValidationError):
            GatewaySettings.model_validate({alias: value})


def test_generated_index_matches_the_generator_output() -> None:
    """`--check` re-renders and diffs byte-for-byte against the committed JSON."""
    result = subprocess.run(  # noqa: S603 — fixed argv, sys.executable owns the child
        [
            sys.executable,
            "-B",
            str(_REPO_ROOT / "scripts" / "codegen" / "gen_config_lite_table.py"),
            "--check",
        ],
        check=False,
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr or result.stdout


def test_all_field_faces_match_the_live_registry() -> None:
    """Every index face (domains/aliases/scopes/capabilities/per-agent/required)
    equals the live registry's derivation — the drift lock for the four
    env-authority projections the review called out by name."""
    reg = _build_registry()
    names = sorted(reg)
    assert set(FIELD_DOMAINS) == set(FIELD_ALIASES) == set(names)
    assert set(FIELD_SCOPES) == set(FIELD_CAPABILITIES) == set(names)
    assert {name: reg[name].domain for name in names} == FIELD_DOMAINS
    assert {name: field_alias(name) for name in names} == FIELD_ALIASES
    assert {name: str(schema_extra(reg[name].info).get("scope")) for name in names} == FIELD_SCOPES
    assert {name: reg[name].capability for name in names} == FIELD_CAPABILITIES
    assert {
        name for name in names if schema_extra(reg[name].info).get("per_agent") is True
    } == PER_AGENT_FIELDS
    assert {
        name
        for name in names
        if isinstance(extra := reg[name].info.json_schema_extra, dict)
        and cast(dict[str, object], extra).get("sensitive") is True
    } == SENSITIVE_FIELDS
    required: set[str] = set()
    for name in names:
        info = cast(FieldInfo, reg[name].info)  # the registry stores FieldInfo behind a Protocol
        if info.default is PydanticUndefined and info.default_factory is None:
            required.add(name)
    assert required == REQUIRED_FIELDS


def test_lite_fields_match_the_registry() -> None:
    """Every boot-path row's (domain, alias) equals the registry's and every
    literal default equals the field's declared default. The manifest's
    membership itself is locked by the generator's own `--check` byte diff."""
    reg = _build_registry()
    assert LITE_FIELDS, "the boot-path index must not be empty"
    for name, row in LITE_FIELDS.items():
        assert isinstance(row, tuple) and len(row) == 6
        domain, alias, kind, default_kind, literal, check = row
        assert domain == reg[name].domain
        assert alias == field_alias(name)
        assert kind in {"str", "int", "float", "bool", "bool_or_none", "path", "csv_str_list"}
        assert default_kind in {
            "literal",
            "none",
            "factory_empty_list",
            "otel_endpoint_from_port",
        }
        assert check in {None, "iana", "port", "eval_allowlist"}
        if default_kind == "literal":
            assert literal == cast(FieldInfo, reg[name].info).default


def test_index_and_reader_live_outside_the_config_package() -> None:
    """Negative assertion: neither the reader nor the data file may move inside
    `base/config/` — `base/host/env/registry` imports them before the package can
    initialize (a package submodule import would re-enter the boot)."""
    table_module = importlib.import_module("base.host.env.config_lite_table")
    module_file = table_module.__file__
    assert module_file is not None
    assert Path(module_file).resolve() == _READER
    assert not (_REPO_ROOT / "base" / "config" / "config_lite_table.py").exists()
    assert not (_REPO_ROOT / "base" / "config" / "config_lite_table.json").exists()
    raw: dict[str, Any] = json.loads(_INDEX.read_text(encoding="utf-8"))
    assert set(raw) == {
        "_generated",
        "lite_fields",
        "field_domains",
        "field_aliases",
        "field_scopes",
        "field_capabilities",
        "per_agent_fields",
        "sensitive_fields",
        "required_fields",
    }
    assert set(raw["lite_fields"]) == set(LITE_FIELDS)
    assert isinstance(PER_AGENT_FIELDS, frozenset) and isinstance(REQUIRED_FIELDS, frozenset)
    assert isinstance(SENSITIVE_FIELDS, frozenset)


@pytest.mark.parametrize(
    "index",
    [LITE_FIELDS, FIELD_DOMAINS, FIELD_ALIASES, FIELD_SCOPES, FIELD_CAPABILITIES],
)
def test_static_indexes_reject_writes_and_keep_copies_independent(
    index: Mapping[str, object],
) -> None:
    name = next(iter(index))
    original = index[name]
    with pytest.raises(TypeError):
        operator.setitem(cast(Any, index), name, "changed")
    copied = dict(index)
    copied[name] = "changed"
    assert index[name] == original


def test_lite_rows_contain_only_immutable_literals() -> None:
    for row in LITE_FIELDS.values():
        assert isinstance(row, tuple)
        assert all(value is None or isinstance(value, str | bool | int | float) for value in row)
