"""Reader of the generated boot-lite static config index (``config_lite_table.json``).

The index is generated by ``scripts/gen_config_lite_table.py`` — run it after any
config-field change; ``--check`` fails on drift. It is JSON, not a generated
Python module, because the all-field faces alone (512 fields x several columns)
exceed the repo's 800-line hard ceiling (``scripts/lint_code_structure.py``, no
exemption), and a data table is what JSON is for (precedent:
``shared/lm/pricing_catalog_archive.json``). This module is the only reader; it
materializes the named surfaces every consumer imports:

- ``LITE_FIELDS`` — the boot-path fields ``shared/config/_lite.py`` resolves
  without pydantic;
- ``FIELD_DOMAINS`` / ``FIELD_ALIASES`` / ``FIELD_SCOPES`` /
  ``FIELD_CAPABILITIES`` / ``PER_AGENT_FIELDS`` — the all-field indexes the
  facade accessors and ``shared/env_registry.py``'s authority projections serve
  without building the registry;
- ``REQUIRED_FIELDS`` — the no-default fields ``_lite.prepare`` requires.

The module lives OUTSIDE the ``shared.config`` package on purpose, like
``shared/config_registry.py``: ``shared/env_registry.py`` (the env-authority
projections that ``load_ava_env`` runs before Settings exists) imports it, and a
package submodule import would execute the ``shared.config`` facade first —
re-entering the boot it is part of.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

_RAW = cast(
    dict[str, Any],
    json.loads(Path(__file__).with_name("config_lite_table.json").read_text(encoding="utf-8")),
)

# name: (domain, env alias, parse kind, default kind, literal default | None, validity check | None)
LITE_FIELDS: dict[str, tuple[str, str, str, str, object, str | None]] = {
    name: (row[0], row[1], row[2], row[3], row[4], row[5])
    for name, row in cast(dict[str, list[Any]], _RAW["lite_fields"]).items()
}

FIELD_DOMAINS: dict[str, str] = _RAW["field_domains"]
FIELD_ALIASES: dict[str, str] = _RAW["field_aliases"]
# The env-authority pass (shared/env_registry.py) reads these two without the registry.
FIELD_SCOPES: dict[str, str] = _RAW["field_scopes"]
FIELD_CAPABILITIES: dict[str, str] = _RAW["field_capabilities"]
PER_AGENT_FIELDS: frozenset[str] = frozenset(_RAW["per_agent_fields"])
# Fields with no default and no factory — the W1 required check in _lite.prepare().
REQUIRED_FIELDS: frozenset[str] = frozenset(_RAW["required_fields"])
