"""Generate `ui/web/src/lib/constants-generated.ts` from backend constants.

Single source of truth: module-level int constants in `shared/live_events.py`
(currently `EVENT_COALESCE_MS` — the SSE live-view event window). The frontend
imports the generated file, so the agent-side coalesce window and the
frontend-side render throttle can never drift apart.

Run manually after changing a source constant, or let pre-commit's
`constants-codegen-fresh` hook fail-loud on drift:
    .venv/bin/python scripts/dump_frontend_constants.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from shared.live_events import EVENT_COALESCE_MS

_OUT = Path("ui/web/src/lib/constants-generated.ts")

_HEADER = """/**
 * This file was auto-generated by scripts/dump_frontend_constants.py.
 * Do not make direct changes to the file.
 * Source of truth: shared/live_events.py (EVENT_COALESCE_MS).
 */

// SSE live-view event window — ~25 FPS. The agent-side event publisher
// coalesces emitted deltas / exec chunks into this window (one event per
// window); the frontend throttles stream re-parse to the same window, so
// producer and consumer stay aligned (at most one render per frame).
export const SSE_EVENT_WINDOW_MS = {coalesce_ms};
"""


def main(out_dir: str | None = None) -> None:
    out = Path(out_dir) / "constants-generated.ts" if out_dir else _OUT
    out.write_text(_HEADER.format(coalesce_ms=EVENT_COALESCE_MS))
    if not out_dir:
        print(f"wrote {out} (SSE_EVENT_WINDOW_MS = {EVENT_COALESCE_MS} ms)")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else None))
