"""Pure-function tests for agent/envelope.py.

`wrap_inbound` is the "message boundary" contract for the agent SYSTEM_PROMPT — if
the format changes, SYSTEM_PROMPT must change in sync. Pin the format for each
source type:
- `system` / `system:<subtype>` → raw text, no wrap (no timestamp)
- `agent:N` → "Agent N [timestamp]:" prefix
- `user` → "User [timestamp]:" prefix
- `watcher:N` → "Watcher (id N) [ts]:" prefix
- unrecognized → ValueError (fail-fast)

Timestamps are generated by `shared.config.now_timestamp()`, mocked to a fixed
value in tests.
"""

from __future__ import annotations

from datetime import UTC

import pytest

from shared.envelope import validate_source, wrap_inbound

_TIMESTAMP = "[2026-05-06 14:32:05]"
_TS = _TIMESTAMP  # shorthand


@pytest.fixture(autouse=True)
def _freeze_timestamp(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock now_timestamp to a fixed value for all tests."""
    monkeypatch.setattr("shared.envelope.now_timestamp", lambda: _TIMESTAMP)


class TestUserSource:
    """`source='user'` —— the human user (the UI). Wraps as "User [ts]:"."""

    def test_user(self) -> None:
        assert wrap_inbound("hi", "user") == f"User {_TS}:\n\nhi"

    def test_user_preserves_multiline(self) -> None:
        content = "line 1\nline 2\n\nline 4"
        assert wrap_inbound(content, "user") == f"User {_TS}:\n\n{content}"

    def test_user_empty_content(self) -> None:
        assert wrap_inbound("", "user") == f"User {_TS}:\n\n"

    def test_legacy_ui_prefix_now_rejected(self) -> None:
        """The old `ui:X` channel namespace is gone — `user` is the only plain
        human source now. Old forms fail-fast rather than silently wrap as
        "User". The one surviving `ui:` form is `ui:page:<name>` (page callback)."""
        for bad in ("ui:web", "ui:telegram", "ui:cli", "ui:slack"):
            with pytest.raises(ValueError, match="Unrecognized inbound source"):
                wrap_inbound("hi", bad)


class TestPageCallback:
    """`source='ui:page:<name>'` — an HTML page the agent started posts back. It
    reads as "User"; the agent recovers which page from <name>."""

    def test_page_callback_wraps_as_user(self) -> None:
        assert wrap_inbound("chose B", "ui:page:compare") == f"User {_TS}:\n\nchose B"

    def test_page_callback_validates(self) -> None:
        validate_source("ui:page:compare")  # no raise


class TestSystemSource:
    def test_system_not_wrapped(self) -> None:
        """source='system' is a framework internal insert, gets [system] prefix, no timestamp."""
        assert wrap_inbound("请梳理并调 ava.compact", "system") == "[system] 请梳理并调 ava.compact"

    @pytest.mark.parametrize(
        "source",
        ["system:rollback", "system:update", "system:compact", "system:health_check"],
    )
    def test_system_subtype_not_wrapped(self, source: str) -> None:
        """source='system:<subtype>' treated same as 'system' — [system] prefix, no timestamp."""
        assert wrap_inbound("raw msg", source) == "[system] raw msg"

    @pytest.mark.parametrize(
        "source",
        ["system:rollback", "system:update", "system:compact", "system:health_check"],
    )
    def test_system_subtype_validates(self, source: str) -> None:
        """validate_source accepts system:<subtype>."""
        validate_source(source)  # no raise


class TestAgentPrefix:
    """`source='agent:N'` — message sent by a peer agent. Includes sender id so the
    receiver knows which peer is talking to it (telling apart multiple children)."""

    def test_agent_prefix_includes_sender_id(self) -> None:
        assert wrap_inbound("hi", "agent:42") == f"Agent 42 {_TS}:\n\nhi"

    def test_agent_prefix_with_multiline_content(self) -> None:
        content = "line 1\nline 2"
        assert wrap_inbound(content, "agent:7") == f"Agent 7 {_TS}:\n\n{content}"

    def test_agent_prefix_not_user_format(self) -> None:
        """agent source must not produce a "User" prefix."""
        out = wrap_inbound("x", "agent:1")
        assert "User messaged" not in out
        assert out.startswith(f"Agent 1 {_TS}:")


# ---- watcher:N -------------------------------------------------------------


class TestWatcherPrefix:
    """`source='watcher:N'` — an inbound delivered from a watcher session (a
    scheduled fire or its exit notice), N is the watcher's session id."""

    def test_watcher_wrap_includes_id(self) -> None:
        assert wrap_inbound("disk 90%", "watcher:42") == f"Watcher (id 42) {_TS}:\n\ndisk 90%"

    def test_watcher_wrap_multiline(self) -> None:
        content = "line 1\nline 2"
        assert wrap_inbound(content, "watcher:7") == f"Watcher (id 7) {_TS}:\n\n{content}"

    def test_watcher_validate_ok(self) -> None:
        validate_source("watcher:0")  # no raise

    def test_watcher_validate_rejects_non_int(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="non-negative-int"):
            validate_source("watcher:abc")

    def test_schedule_source_is_valid(self) -> None:
        validate_source("schedule:7")  # no raise
        assert wrap_inbound("consolidate now", "schedule:7") == (
            f"Schedule (id 7) {_TS}:\n\nconsolidate now"
        )

    def test_schedule_rejects_non_int(self) -> None:
        import pytest

        for bad in ("schedule:abc", "schedule:1:expired"):
            with pytest.raises(ValueError, match="non-negative-int"):
                validate_source(bad)

    def test_shell_source_is_valid(self) -> None:
        # `shell:N` — the completion notice of a background shell command
        # (ava.shell.run_background), N is the shell session id.
        validate_source("shell:5")  # no raise
        assert wrap_inbound("build exited with code 0", "shell:5") == (
            f"Shell session (id 5) {_TS}:\n\nbuild exited with code 0"
        )

    def test_shell_rejects_non_int(self) -> None:
        import pytest

        for bad in ("shell:abc", "shell:1-build"):
            with pytest.raises(ValueError, match="non-negative-int"):
                validate_source(bad)

    def test_monitor_still_rejected(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="Unrecognized inbound source"):
            validate_source("monitor:1")


class TestUnknownSource:
    @pytest.mark.parametrize("source", ["web", "telegram", "kernel", "eval", "tiktok", ""])
    def test_unknown_source_raises(self, source: str) -> None:
        """Old source without prefix / typo / outside the four categories → ValueError (fail-fast)."""
        with pytest.raises(ValueError, match="Unrecognized inbound source"):
            wrap_inbound("x", source)

    def test_unknown_source_error_lists_valid_options(self) -> None:
        """error message must list legal source forms so the caller sees correct format at a glance.
        mutmut exposed that the help text (must be 'system' / 'agent:N' / ...) could be
        typo'd / case-changed without this test catching it (PR follow-up)."""
        with pytest.raises(ValueError) as exc_info:
            wrap_inbound("x", "bad")
        msg = str(exc_info.value)
        # Help text format lock
        assert "must be" in msg
        assert "'system'" in msg
        assert "'system:<subtype>'" in msg
        assert "'agent:N'" in msg
        assert "'user'" in msg
        assert "'ui:page:<name>'" in msg
        assert "'watcher:N'" in msg


class TestMessageTimestampsOff:
    """`settings.general.message_timestamps=False` — strips timestamps from all source
    prefixes, with no trailing space before the colon."""

    @pytest.fixture(autouse=True)
    def _disable(self, monkeypatch: pytest.MonkeyPatch) -> None:
        from shared.config import settings

        monkeypatch.setattr(settings.general, "message_timestamps", False)

    def test_user_no_timestamp(self) -> None:
        assert wrap_inbound("hi", "user") == "User:\n\nhi"

    def test_agent_no_timestamp(self) -> None:
        assert wrap_inbound("hi", "agent:5") == "Agent 5:\n\nhi"

    def test_watcher_no_timestamp(self) -> None:
        assert wrap_inbound("hi", "watcher:7") == "Watcher (id 7):\n\nhi"

    def test_system_unchanged(self) -> None:
        # `system` and `system:*` get [system] prefix, no timestamp regardless of flag.
        assert wrap_inbound("raw", "system") == "[system] raw"
        assert wrap_inbound("raw", "system:rollback") == "[system] raw"


class TestCreatedAtParameter:
    """`created_at=` parameter — when a real creation time is passed, the
    envelope timestamp uses that wall-clock rather than the current time,
    so the agent sees a chronological timeline even when several messages
    are claimed in one batch."""

    def test_user_with_created_at(self) -> None:
        from datetime import datetime

        created = datetime(2026, 6, 21, 10, 30, 0, tzinfo=UTC)
        # created_at is UTC 10:30, which is PDT 03:30
        out = wrap_inbound("hi", "user", created_at=created)
        assert "[2026-06-21 03:30:00]" in out
        assert out == "User [2026-06-21 03:30:00]:\n\nhi"

    def test_agent_with_created_at(self) -> None:
        from datetime import datetime

        created = datetime(2026, 6, 21, 14, 0, 0, tzinfo=UTC)
        # UTC 14:00 = PDT 07:00
        out = wrap_inbound("hey", "agent:5", created_at=created)
        assert "[2026-06-21 07:00:00]" in out
        assert out == "Agent 5 [2026-06-21 07:00:00]:\n\nhey"

    def test_without_created_at_uses_now(self) -> None:
        """When created_at is None, fallback to now_timestamp (existing behavior)."""
        out = wrap_inbound("hi", "user")
        assert _TIMESTAMP in out  # frozen by fixture

    def test_system_ignores_created_at(self) -> None:
        """source='system' and subtypes get [system] prefix, created_at is ignored (no ts)."""
        from datetime import datetime

        created = datetime(2026, 1, 1, tzinfo=UTC)
        assert wrap_inbound("raw", "system", created_at=created) == "[system] raw"
        assert wrap_inbound("raw", "system:rollback", created_at=created) == "[system] raw"

    def test_watcher_with_created_at(self) -> None:
        from datetime import datetime

        created = datetime(2026, 6, 21, 20, 0, 0, tzinfo=UTC)
        # UTC 20:00 = PDT 13:00
        out = wrap_inbound("alert", "watcher:7", created_at=created)
        assert "[2026-06-21 13:00:00]" in out


class TestCreatedAtWithTimestampsOff:
    """When message_timestamps is off, created_at doesn't add a ts either."""

    @pytest.fixture(autouse=True)
    def _disable(self, monkeypatch: pytest.MonkeyPatch) -> None:
        from shared.config import settings

        monkeypatch.setattr(settings.general, "message_timestamps", False)

    def test_user_no_ts_even_with_created_at(self) -> None:
        from datetime import datetime

        created = datetime(2026, 6, 21, 10, 0, 0, tzinfo=UTC)
        assert wrap_inbound("hi", "user", created_at=created) == "User:\n\nhi"

    def test_agent_no_ts_even_with_created_at(self) -> None:
        from datetime import datetime

        created = datetime(2026, 6, 21, 10, 0, 0, tzinfo=UTC)
        assert wrap_inbound("hi", "agent:5", created_at=created) == "Agent 5:\n\nhi"


class TestWeekdayFlag:
    """`message_timestamp_weekday` reaches the `created_at` path too.

    Production inbound rows always carry a creation time, so that path — not
    the `now_timestamp` fallback — is the one every user message takes. A flag
    honoured only by `now_timestamp` gave the agent two timestamp formats in
    one conversation: no weekday on inbound, weekday on exec output and
    lifecycle markers.
    """

    @staticmethod
    def _wrap(monkeypatch: pytest.MonkeyPatch, *, weekday: bool) -> str:
        from datetime import datetime

        from shared.config import settings

        monkeypatch.setattr(settings.general, "message_timestamp_weekday", weekday)
        # UTC 10:30 on a Sunday = PDT 03:30
        created = datetime(2026, 6, 21, 10, 30, 0, tzinfo=UTC)
        return wrap_inbound("hi", "user", created_at=created)

    def test_weekday_on(self, monkeypatch: pytest.MonkeyPatch) -> None:
        assert self._wrap(monkeypatch, weekday=True) == "User [2026-06-21 Sun 03:30:00]:\n\nhi"

    def test_weekday_off(self, monkeypatch: pytest.MonkeyPatch) -> None:
        assert self._wrap(monkeypatch, weekday=False) == "User [2026-06-21 03:30:00]:\n\nhi"

    def test_no_timezone_suffix_either_way(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """No `%Z` in either shape — the timezone is declared once, in the
        standing context note (`agent.graph._context_notes.timezone_note`),
        not repeated on every stamp. `settings.general.timezone` is
        cluster-pinned, so the suffix was a constant, and an ambiguous one
        (`PDT` vs `PST` for one unchanged setting; `CST` for two zones)."""
        for weekday in (True, False):
            out = self._wrap(monkeypatch, weekday=weekday)
            assert "PDT" not in out and "PST" not in out
            assert out.endswith(":00]:\n\nhi")

    def test_created_at_and_now_agree(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """Both producers render one shape — the docstring claim, enforced.

        `now_timestamp` is unmocked here (the autouse freeze is undone) so the
        two real code paths are compared against each other.
        """
        import re
        from datetime import datetime

        from shared.config import now_timestamp, settings

        monkeypatch.setattr("shared.envelope.now_timestamp", now_timestamp)
        for weekday in (True, False):
            monkeypatch.setattr(settings.general, "message_timestamp_weekday", weekday)
            day = r"[A-Z][a-z]{2} " if weekday else ""
            shape = rf"^User \[\d{{4}}-\d{{2}}-\d{{2}} {day}\d{{2}}:\d{{2}}:\d{{2}}\]:$"
            for out in (
                wrap_inbound("hi", "user"),
                wrap_inbound("hi", "user", created_at=datetime.now(UTC)),
            ):
                assert re.match(shape, out.split("\n")[0]), out
