"""agent/graph/_exec_output.py's wrap_code_output pure function test.

`wrap_code_output` is the envelope fed to LLM — agent relies on "Code execution output" prefix to identify subprocess feedback. Anchor format; changing one side will red the other side test.

`output` single param = subprocess stdout + stderr merged stream (`stderr=STDOUT`, equivalent shell 2>&1), preserves real timing order; no longer separate stdout / stderr.
return code not in envelope — framework internal signal (42 / 43) goes via ToolMessage metadata.

Timestamp generated by `shared.config.now_timestamp()`, mocked to fixed value in tests.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from agent.graph._exec_output import wrap_code_output

_TIMESTAMP = "[2026-05-06 14:32:05 PDT]"
_TS = _TIMESTAMP  # shorthand


@pytest.fixture(autouse=True)
def _freeze_timestamp(monkeypatch: pytest.MonkeyPatch) -> None:
    """Mock now_timestamp for all tests to fixed value."""
    monkeypatch.setattr("agent.graph._exec_output.now_timestamp", lambda: _TIMESTAMP)


def test_wrap_code_output_structured():
    """code_output envelope contains output, **does not** contain exit code."""
    out = wrap_code_output("hello\nwarn\n")
    assert "Code execution output" in out
    assert _TS in out
    assert "hello" in out and "warn" in out
    assert "[exit" not in out


def test_wrap_code_output_cancelled_marker():
    """When cancelled, carries [cancelled by user] marker."""
    out = wrap_code_output("part\n", cancelled=True)
    assert "[cancelled by user]" in out
    assert _TS in out
    assert "part" in out


def test_wrap_code_output_appends_trailing_newline_when_missing():
    """When output lacks trailing \\n, envelope still normalizes to single line — nothing to join afterwards, mainly for more stable frontend rendering."""
    out = wrap_code_output("partial output")
    assert "partial output" in out
    assert _TS in out


def test_wrap_code_output_no_stderr_marker_in_envelope():
    """stdout/stderr already merged, envelope should not have '--- stderr ---' separator marker — keeping it directly contradicts 'merged stream' design."""
    out = wrap_code_output("hello\nTraceback (most recent call last):\n  ...\n")
    assert "--- stderr ---" not in out


def test_wrap_code_output_no_output_marker_when_empty():
    """When output is empty, show '(no output)' — explicitly tell agent code ran but produced no output (avoid empty envelope making LLM mistakenly think exec failed/didn't run)."""
    out = wrap_code_output("")
    assert "Code execution output" in out
    assert "(no output)" in out
    assert _TS in out


def test_wrap_code_output_no_output_marker_omitted_when_output_present():
    """When output present, don't add '(no output)' marker — marker is only fallback for empty envelope."""
    out = wrap_code_output("real output\n")
    assert "(no output)" not in out


def test_wrap_code_output_no_output_marker_with_cancelled():
    """Under cancel path, even if output empty, add '(no output)' marker — agent sees [cancelled by user] + (no output) knows it was interrupted and produced nothing."""
    out = wrap_code_output("", cancelled=True)
    assert "[cancelled by user]" in out
    assert "(no output)" in out
    assert _TS in out


def test_wrap_code_output_header_body_double_newline_split():
    """Between header and body use \\n\\n separator (same contract as wrap_inbound, frontend splitEnvelope splits header/body by this)."""
    out = wrap_code_output("body line\n")
    # header must be followed by double \n
    assert f"Code execution output {_TS}:\n\nbody line" in out


def test_wrap_code_output_truncates_keeps_both_ends_and_writes_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Exceeds exec_output_max_chars → keep head + tail, cut middle, full output written to tmp file and path reported.
    Head carries help() overview / overview, tail carries error / result, both ends must survive."""
    import ava
    from agent.graph import _exec_output

    monkeypatch.setattr(ava._boot, "_agent_id", 7)
    monkeypatch.setattr(_exec_output, "_overflow_dir", lambda: tmp_path / "overflow")

    limit = 1000
    head_marker = "HEAD_START"
    tail_marker = "TAIL_END"
    big = head_marker + ("X" * 5000) + ("M" * (limit * 3)) + ("Y" * 5000) + tail_marker
    out = wrap_code_output(big, max_chars=limit)

    assert head_marker in out, "head must be preserved (help overview at start)"
    assert tail_marker in out, "tail must be preserved (error / result usually at end)"
    assert "M" * (limit * 3) not in out, "middle should be cut"
    assert "output truncated" in out and "omitted" in out, (
        "marker indicates truncation + how much omitted"
    )

    # path is reported, and the file holds the complete output
    files = list((tmp_path / "overflow").glob("exec_*.txt"))
    assert len(files) == 1
    assert str(files[0]) in out, "complete output path must be reported to agent"
    assert files[0].read_text(encoding="utf-8") == big


def test_wrap_code_output_overflow_files_pruned_to_keep_limit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Same agent repeatedly overflows keeps only recent N, prevents workspace infinite pile-up."""
    import ava
    from agent.graph import _exec_output

    monkeypatch.setattr(ava._boot, "_agent_id", 7)
    monkeypatch.setattr(_exec_output, "_overflow_dir", lambda: tmp_path / "overflow")
    monkeypatch.setattr(_exec_output, "_OVERFLOW_KEEP", 3)

    for _ in range(5):
        wrap_code_output("Z" * 2000, max_chars=100)
    files = list((tmp_path / "overflow").glob("exec_*.txt"))
    assert len(files) == 3, "only keep recent 3"


def test_wrap_code_output_no_truncation_when_under_limit():
    """≤ exec_output_max_chars returns directly unchanged, no marker added."""
    from shared.config import settings

    just_under = "y" * (settings.sandbox.exec_output_max_chars - 100)
    out = wrap_code_output(just_under)
    assert "output truncated" not in out
    assert just_under in out


def test_wrap_code_output_timed_out_marker():
    """When timed out, carries [timeout after Ns] marker (N from settings.sandbox.exec_timeout_seconds), no cancel marker."""
    out = wrap_code_output("part\n", timed_out=True, timeout_seconds=60)
    assert "[timeout after 60s]" in out
    assert "[cancelled by user]" not in out
    assert "part" in out


def test_wrap_code_output_timed_out_carries_strategy_hint():
    """timeout envelope is agent's only clue to change strategy — hint must name long-task primitive; non-timeout path no hint."""
    out = wrap_code_output("part\n", timed_out=True, timeout_seconds=60)
    assert "run_background" in out
    assert "ava.watcher.launch" in out
    assert "run_background" not in wrap_code_output("part\n")
    assert "run_background" not in wrap_code_output("part\n", cancelled=True)


def test_wrap_code_output_timed_out_empty():
    """Under timeout path, even output empty, adds '(no output)' marker, hint still present."""
    out = wrap_code_output("", timed_out=True, timeout_seconds=60)
    assert "[timeout after 60s]" in out
    assert "(no output)" in out
    assert "run_background" in out
    assert "[cancelled by user]" not in out


def test_wrap_code_output_cancelled_wins_over_timed_out_marker():
    """When both cancel and timed_out True, cancel marker shows (priority).
    However wrap_code_output only receives one bool — caller (exec_node) guarantees mutual exclusion.
    Here verify when cancelled=True, no timeout marker appears."""
    out = wrap_code_output("data\n", cancelled=True, timeout_seconds=60)
    assert "[cancelled by user]" in out
    assert "[timeout after 60s]" not in out


def test_wrap_code_output_no_timestamp_when_disabled(monkeypatch: pytest.MonkeyPatch):
    """settings.general.message_timestamps=False → header drops the timestamp and the
    space before the colon, keeping any marker intact."""
    from shared.config import settings

    monkeypatch.setattr(settings.general, "message_timestamps", False)
    assert wrap_code_output("hello\n").startswith("Code execution output:\n\n")
    assert _TS not in wrap_code_output("hello\n")
    # marker survives, still no timestamp / stray space
    out = wrap_code_output("part\n", cancelled=True)
    assert "Code execution output [cancelled by user]:\n\n" in out
    assert _TS not in out
