/**
 * This file was auto-generated by scripts/dump_frontend_constants.py.
 * Do not make direct changes to the file.
 * Source of truth: shared/live_events.py (EVENT_COALESCE_MS).
 */

// SSE live-view event window — ~25 FPS. The agent-side event publisher
// coalesces emitted deltas / exec chunks into this window (one event per
// window); the frontend throttles stream re-parse to the same window, so
// producer and consumer stay aligned (at most one render per frame).
export const SSE_EVENT_WINDOW_MS = 40;
