"""Reader of the generated boot-lite static config index (``config_lite_table.json``).

The index is generated by ``scripts/codegen/gen_config_lite_table.py`` — run it after any
config-field change; ``--check`` fails on drift. It is JSON, not a generated
Python module, because the all-field faces alone (512 fields x several columns)
exceed the repo's 800-line hard ceiling (``scripts/lint/code_structure.py``, no
exemption), and a data table is what JSON is for (precedent:
``base/lm/pricing/pricing_catalog_archive.json``). This module is the only reader; it
materializes the named surfaces every consumer imports:

- ``LITE_FIELDS`` — the boot-path fields ``base/config/_lite.py`` resolves
  without pydantic;
- ``FIELD_DOMAINS`` / ``FIELD_ALIASES`` / ``FIELD_SCOPES`` /
  ``FIELD_CAPABILITIES`` / ``PER_AGENT_FIELDS`` — the all-field indexes the
  facade accessors and ``base/host/env/registry.py``'s authority projections serve
  without building the registry;
- ``REQUIRED_FIELDS`` — the no-default fields ``_lite.prepare`` requires.

The module lives OUTSIDE the ``base.config`` package on purpose, like
``base/host/env/config_registry.py``: ``base/host/env/registry.py`` (the env-authority
projections that ``load_ava_env`` runs before Settings exists) imports it, and a
package submodule import would execute the ``base.config`` facade first —
re-entering the boot it is part of.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from types import MappingProxyType
from typing import Any, cast

LiteField = tuple[str, str, str, str, object, str | None]


def _read_index() -> dict[str, object]:
    """Parse once; only immutable index values survive the local JSON payload."""
    raw = cast(
        dict[str, Any],
        json.loads(Path(__file__).with_name("config_lite_table.json").read_text(encoding="utf-8")),
    )
    lite_fields: dict[str, LiteField] = {
        name: (row[0], row[1], row[2], row[3], row[4], row[5])
        for name, row in cast(dict[str, list[Any]], raw["lite_fields"]).items()
    }
    return {
        "lite_fields": MappingProxyType(lite_fields),
        "field_domains": MappingProxyType(raw["field_domains"]),
        "field_aliases": MappingProxyType(raw["field_aliases"]),
        "field_scopes": MappingProxyType(raw["field_scopes"]),
        "field_capabilities": MappingProxyType(raw["field_capabilities"]),
        "per_agent_fields": frozenset(raw["per_agent_fields"]),
        "required_fields": frozenset(raw["required_fields"]),
    }


_INDEX = MappingProxyType(_read_index())

# name: (domain, env alias, parse kind, default kind, literal default | None, validity check | None)
LITE_FIELDS = cast(Mapping[str, LiteField], _INDEX["lite_fields"])
FIELD_DOMAINS = cast(Mapping[str, str], _INDEX["field_domains"])
FIELD_ALIASES = cast(Mapping[str, str], _INDEX["field_aliases"])
# The env-authority pass (base/host/env/registry.py) reads these two without the registry.
FIELD_SCOPES = cast(Mapping[str, str], _INDEX["field_scopes"])
FIELD_CAPABILITIES = cast(Mapping[str, str], _INDEX["field_capabilities"])
PER_AGENT_FIELDS = cast(frozenset[str], _INDEX["per_agent_fields"])
# Fields with no default and no factory — the W1 required check in _lite.prepare().
REQUIRED_FIELDS = cast(frozenset[str], _INDEX["required_fields"])
